port-labs/port-docs

docs/complete-use-cases/software-catalog.md
Remove unnecessary property in software catalog example
- Software Catalog (`/complete-use-cases/software-catalog`)
=> PORT-1975 Remove unnecessary property in example

docs/software-catalog/blueprint/blueprint.md
Updated user format string property's description
=> PORT-2087-user-property-remove-the-email-format-validationgit_checkout_-b_PORT-2087-user-property-remove-the-email-format-validation

docs/platform-overview.md, docs/self-service-actions/github-workflow/examples/run-service-deployment.md, docs/self-service-actions/github-workflow/github-workflow.md, docs/self-service-actions/self-service-actions-deep-dive/_category_.json, docs/self-service-actions/self-service-actions-deep-dive/action-runs-tutorial.md, docs/self-service-actions/self-service-actions-deep-dive/self-service-actions-deep-dive.md, docs/self-service-actions/self-service-actions.md, docs/self-service-actions/webhook/local-debugging-webhook.md, docs/self-service-actions/webhook/port-execution-agent/quickstart.md, docs/software-catalog/blueprint/blueprint.md, docs/software-catalog/blueprint/timer-properties.md
make action runs tutorial a subpage of deep dive
- ...
- ...
=> PORT-2798 Make self-service-actions deep dive a category

docs/customize-pages-dashboards-and-plugins/widgets/embedded-url/embedded-url.md
=> Fix mistakes in embedded url

docs/self-service-actions/webhook/port-execution-agent/quickstart.md
Fix port execution agent installation command
- Port Execution Agent Quickstart (`/self-service-actions/webhook/port-execution-agent/quickstart.md)
=> fix port execution agent installation command

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/opsgenie.md
This PR adds a section that points users on how to ingest OpsGenie's on-call data into Port
https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/webhook/examples/opsgenie
=> Update OpsGenie to include who is on call

docs/build-your-software-catalog/sync-data-to-catalog/aws/examples.md
Remove region relation from aws examples
- AWS Examples (`/build-your-software-catalog/sync-data-to-catalog/aws/examples.md`)
=> remove region from aws examples

docs/promote-scorecards/tutorial.md
=> PORT-3970 Fix wrong API URL in scorecards docs

docs/build-your-software-catalog/sync-data-to-catalog/aws/aws.md
Add support for itemsToParse to AWS exporter.
- AWS Exporter (`/build-your-software-catalog/sync-data-to-catalog/aws/aws.md`)
=> Add itemsToParse to AWS exporter

docs/guides-and-tutorials/scaffold-a-new-service.md
Switched the Github workflow from the deprecated octobay to use our own cookiecutter action, with slightly altered inputs to support the quickstart guide blueprint.
- ...
- ...
=> changed the workflow to uses our own action

docs/create-self-service-experiences/setup-backend/github-workflow/examples/create-github-secret.md, docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/scaffold-repositories-using-cookiecutter.md
Added a Port Action example which creates a GitHub Secret using a GitHub workflow.
- GitHub Workflow (`/create-self-service-experiences/setup-backend/github-workflow/examples/create-github-secret`)
- Jenkins Workflow (`/create-self-service-experiences/setup-backend/jenkins-workflow/examples/scaffold-repositories-using-cookiecutter`)
=> Added create-github-secret workflow

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/sonarqube.md
Clients were unable to ingest Sonarqube cloud analysis into Port due to differences (case sensitivity) in the Sonarqube webhook request header signature field
docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/sonarqube.md
=> Update sonarqube webhook request header

docs/create-self-service-experiences/setup-backend/github-workflow/examples/create-github-secret.md, docs/create-self-service-experiences/setup-ui-for-action/user-inputs/secret.md
just switched the secret property examples from fernet to the newer (and not depracated aes256-gcm)
=> PORT-5159-remove-all-mentions-of-fernet-in-docs-other-than-the-depracated-part

docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/advanced.md, docs/build-your-software-catalog/sync-data-to-catalog/git/github/advanced.md
enableMergeEntity default true in gitops github bitbucket
- Bitbucket Advanced (`docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/advanced.md`)
- GitHub Advanced (`/build-your-software-catalog/sync-data-to-catalog/git/github/advanced.md`)
=> enableMergeEntity default true in gitops github bitbucket

docs/create-self-service-experiences/setup-backend/azure-pipeline/examples/scaffold-repositories-using-cookiecutter.md, docs/create-self-service-experiences/setup-backend/gitlab-pipeline/examples/deploy-s3-bucket-crossplane.md
Fixed links to be absolute
- (`/create-self-service-experiences/setup-backend/azure-pipeline/examples/scaffold-repositories-using-cookiecutter`)
- (`/create-self-service-experiences/setup-backend/gitlab-pipeline/examples/deploy-s3-bucket-crossplane`)
=> changed links to absolute

docs/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty.md
The PagerDuty service oncall property was not aligned with the most recent ocean update. This PR updates the blueprint and config mapping
=> Update Pagerduty oncall config mapping and blueprint

docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/newrelic.md
After https://github.com/port-labs/helm-charts/pull/49 is merged we can merge this, as we no longer need to pass it as `--set-string` as it will be handled in the helm chart
=> [Integration][NewRelic] Update the `--set-string` to `--set`

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/jenkins/_example_jenkins_build_webhook_configuration.mdx
https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/webhook/examples/jenkins
The timestamp is UNIX and it needs to be divided by 1000 and then map to date, otherwise it starts to fail
=> Jenkins Webhook - todate timestamp

docs/integrations-index.md
Updated integrations index with 2 examples of self service actions from :
https://github.com/port-labs/self-service-actions-examples/tree/main
=> Updated integrations index

docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/installation-methods/_category_.json, docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/installation-methods/argocd.md, docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/installation-methods/helm.md, docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/installation-methods/installation-methods.md, docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/port-execution-agent.md, docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/usage.md
re-organzied port-agent and added argocd installation method
- helm method (`/create-self-service-experiences/setup-backend/webhook/port-execution-agent/installation-methods/helm.md`)
- argocd method (`/create-self-service-experiences/setup-backend/webhook/port-execution-agent/installation-methods/argocd.md`)
- methods (`/create-self-service-experiences/setup-backend/webhook/port-execution-agent/installation-methods/installation-methods.md`)
- usage (`/create-self-service-experiences/setup-backend/webhook/port-execution-agent/usage.md`)
- main category (`/create-self-service-experiences/setup-backend/webhook/port-execution-agent/port-execution-agent.md`)
=> re-organzied port-agent and added argocd installation method

docs/integrations-index.md
Added integrations for:
- [Github packages](https://github.com/port-labs/example-github-packages)
- [ECR images (Repository)](https://github.com/port-labs/example-ecr-images):  
- [JFrog X-ray Alerts (Repository and Artifact)](https://github.com/port-labs/example-jfrog-xray-alerts)
- [JFrog container images (builds and repository)](https://github.com/port-labs/example-jfrog-container-images)
- Integrations Index (`/integrations-index`)
- Integrations Index (`/integrations-index`)
=> PORT-6064 | Update Integrations Index on Port documentation with newly developed Python scripts

docs/guides-and-tutorials/scaffold-a-new-service.md
Adding a reminder to users to update the org name in the template `.yaml` file. Without doing so, the self-service action will fail and logs from GitHub are not understood easily enough to point this out to users who copy and paste the template without modifying the organization name. It is also unclear which org should be specified on line 19 (Port or GitHub).
- `docs/guides-and-tutorials/scaffold-a-new-service.md`
=> remind user to change org name

docs/build-your-software-catalog/sync-data-to-catalog/iac/terraform-cloud/terraform-cloud.md
=> removed some redundant wording in terraform doc

docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/aggregation-property/aggregation-property.md
Update for release - https://github.com/port-labs/terraform-provider-port-labs/releases/tag/v1.9.0 
- ...
- ...
=> update resources to `port_aggregation_properties` instead of `port_aggregation_property`

docs/guides-and-tutorials/let-developers-enrich-services-using-gitops.md
In the [enriching services tutorial](https://docs.getport.io/guides-and-tutorials/let-developers-enrich-services-using-gitops) where [creating a frontend action](https://docs.getport.io/guides-and-tutorials/let-developers-enrich-services-using-gitops#setup-the-actions-frontend) is described, the "New input" button is called "Add input," which is not the same as in the UI. See below:
- Let developers enrich services using Gitops (`docs/guides-and-tutorials/let-developers-enrich-services-using-gitops.md`)
=> corrected 'new input' button naming

docs/integrations-index.md
Small spelling correction of "Dependebot" to "Dependabot"
- Integrations index (`/integrations-index/`)
=> Update correcting small spelling error on integrations-index.md

docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/_gitlab_exporter_example_merge_request_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/installation.md
Fixed broken link for GitLab system hooks. Added `calculationProperties` and `calculationProperties` to GitLab merge request blueprint example.
Previously used broken GitLab system hook link was [this](https://docs.gitlab.com/ee/system_hooks/system_hooks.html). By not including `calculationProperties` and `mirrorProperties`, the example merge request blueprint was not able to be used as it was displayed here.
- docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/_gitlab_exporter_example_merge_request_blueprint.mdx
- docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/installation.md
=> fix broken gitlab link and add blueprint info

archive/_tutorial.md, archive/package-dependency-mapping.md, docs/build-your-software-catalog/sync-data-to-catalog/api/ci-cd/azure-pipelines/examples.md, docs/build-your-software-catalog/sync-data-to-catalog/api/ci-cd/circleci-workflow/examples.md, docs/build-your-software-catalog/sync-data-to-catalog/api/ci-cd/gitlab-pipelines/examples.md, docs/build-your-software-catalog/sync-data-to-catalog/api/ci-cd/jenkins-deployment/examples.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/event-based-updates.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty.md, docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/installation-methods/argocd.md, docs/create-self-service-experiences/setup-ui-for-action/advanced-form-configurations.md, docs/promote-scorecards/promote-scorecards.md
Fixed a than/then typo and it's/its typos.
- Archived docs
- Examples (`/build-your-software-catalog/sync-data-to-catalog/api/ci-cd/azure-pipelines/examples`)
- Examples (`/build-your-software-catalog/sync-data-to-catalog/api/ci-cd/circleci-workflow/examples`)
- Examples (`/build-your-software-catalog/sync-data-to-catalog/api/ci-cd/gitlab-pipelines/examples`)
- Examples (`/build-your-software-catalog/sync-data-to-catalog/api/ci-cd/jenkins-deployment/examples`)
- Event-Based Updates (`/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/event-based-updates`)
- PagerDuty (`/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty`)
- ArgoCD (`/create-self-service-experiences/setup-backend/webhook/port-execution-agent/installation-methods/argocd`)
- …
=> Fix small typos

docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/aws-cost.md
Updating AWS cost documentation to:
- Ensure user adds actual name of S3 bucket created in step one when checking to see if CUR has been created
- Provide a description of what the user should be looking for when checking to see if CUR has been created
- Add link to and example cloning method for `port-aws-cost-exporter` repo (not currently listed, and necessary to complete local implementation)
- Revised GitHub Actions Workflow repository variables to remove duplicate `AWS_ACCESS_KEY_ID` and replace with `AWS_ACCESS_KEY_SECRET`)
- AWS Cost doc (`build-your-software-catalog/sync-data-to-catalog/cloud-cost/aws-cost.md`)
=> 20240205 aco

docs/build-your-software-catalog/sync-data-to-catalog/jira/jira.md
The  blueprint schemas defined in the Jira ocean docs do not have these top level properties
"mirrorProperties": {},
"calculationProperties": {},
"aggregationProperties": {},
This PR fixes it.
docs/build-your-software-catalog/sync-data-to-catalog/jira/jira.md
=> Add top level blueprint props Jira Ocean docs

docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace.md
Users of the Dynatrace integration face permissions error during healthcheck. This is due to a missing scope and wrong host URL. This PR adds that context to the documentation.
- Dynatrace (`docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace.md`)
=> Added notes to explain host url and token scopes

docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/newrelic.md, docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/sentry.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/kubecost.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost.md, docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk/snyk.md, docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md, docs/build-your-software-catalog/sync-data-to-catalog/feature-management/launchdarkly.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/firehydrant.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/opsgenie.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/servicenow.md, docs/build-your-software-catalog/sync-data-to-catalog/jenkins/jenkins.md
Added `resources` key to integration configurations which do not have them
- New Relic (`/build-your-software-catalog/sync-data-to-catalog/apm-alerting/newrelic`)
- Sentry (`/build-your-software-catalog/sync-data-to-catalog/apm-alerting/sentry`)
- Kubecost (`/build-your-software-catalog/sync-data-to-catalog/cloud-cost/kubecost`)
- Opencost (`/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost`)
- Snyk (`/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk/snyk`)
- Wiz (`/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz`)
- Launchdarkly (`/build-your-software-catalog/sync-data-to-catalog/feature-management/launchdarkly`)
- FireHydrant (`/build-your-software-catalog/sync-data-to-catalog/incident-management/firehydrant`)
- …
=> PORT-7713 | Some configuration mappings in the docs do not have the "resources:" text

docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/example-project/_azuredevops_exporter_example_project_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/example-project/_azuredevops_exporter_example_project_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/examples.md
Added blueprint and mapping configs examples as to docs.
Path for the updated docs
- Blueprint (`platform-overview/port-components/blueprint](http://localhost:4000/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/examples#mapping-projects`)
=> PORT-7714 | Update Azure Devops docs with project mapping and blueprint

docs/create-self-service-experiences/setup-backend/webhook/local-debugging-webhook.md
@dhatcher42 was trying to follow the Debugging Webhooks locally guide, and was getting an error during the validation of the webhook request step. The validation error occurs due to the body of the request being undefined since we're not using any express middle-ware to read it.
Debugging Webhooks locally - /create-self-service-experiences/setup-backend/webhook/local-debugging-webhook/#creating-a-small-example-server-in-nodejs
=> Using express.json to get the request body as JSON

docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/basic-example.md
Removed .status.conditions from v1/pods kind in the k8s example
This property causes many requests for updates in pods.
- Example k8s (`/build-your-software-catalog/sync-data-to-catalog/kubernetes/basic-example)
=> removed status.conditions from v1/pods example

docs/build-your-software-catalog/custom-integration/api/ci-cd/_ci_example_action.mdx, docs/create-self-service-experiences/setup-backend/github-workflow/examples/argocd/rollback-argocd-deployment.md, docs/create-self-service-experiences/setup-backend/github-workflow/examples/broadcast-api-consumers-message.md, docs/create-self-service-experiences/setup-backend/github-workflow/examples/kubernetes/change-replica-count.md, docs/create-self-service-experiences/setup-backend/github-workflow/examples/kubernetes/manage-clusters.md, docs/create-self-service-experiences/setup-backend/github-workflow/examples/lock-and-unlock-service-in-port.md, docs/create-self-service-experiences/setup-backend/github-workflow/examples/nudge-pr-reviewers.md, docs/create-self-service-experiences/setup-backend/github-workflow/examples/open-slack-channel.md, docs/create-self-service-experiences/setup-backend/github-workflow/examples/promote-to-production.md, docs/guides-and-tutorials/iam-permissions-guide.md
Update these actions to use the new actions structure
docs/create-self-service-experiences/setup-backend/github-workflow/examples/kubernetes/manage-clusters.md
docs/create-self-service-experiences/setup-backend/github-workflow/examples/promote-to-production.md
docs/create-self-service-experiences/setup-backend/github-workflow/examples/broadcast-api-consumers-message.md
docs/create-self-service-experiences/setup-backend/github-workflow/examples/manage-pull-requests.md
docs/create-self-service-experiences/setup-backend/github-workflow/examples/nudge-pr-reviewers.md
docs/create-self-service-experiences/setup-backend/github-workflow/examples/open-slack-channel.md
docs/create-self-service-experiences/setup-backend/github-workflow/examples/argocd/rollback-argocd-deployment.md …
=> Port 7791 update GitHub actions for k8s slack and more

docs/create-self-service-experiences/setup-backend/github-workflow/examples/Datadog/trigger-datadog-incident.md, docs/create-self-service-experiences/setup-backend/github-workflow/examples/Jira/change-status-and-assignee-of-jira-ticket.md, docs/create-self-service-experiences/setup-backend/github-workflow/examples/Jira/open-jira-issue-with-automatic-label.md, docs/create-self-service-experiences/setup-backend/github-workflow/examples/Jira/report-a-bug.md, docs/create-self-service-experiences/setup-backend/github-workflow/examples/SonarQube/add-tags-to-sonarqube-project.md
Since the payload from Port actions are changing, this task involves updating the action blueprint and respective 
GitHub actions for Jira, Sonarqube and Datadog to match the new format
- Trigger Datadog incident (`docs/create-self-service-experiences/setup-backend/github-workflow/examples/Datadog/trigger-datadog-incident.md`)
- Change status and assignee of Jira ticket (`docs/create-self-service-experiences/setup-backend/github-workflow/examples/Jira/change-status-and-assignee-of-jira-ticket.md`)
- Open Jira issue with automatic label (`docs/create-self-service-experiences/setup-backend/github-workflow/examples/Jira/open-jira-issue-with-automatic-label.md`)
- Report a bug (`docs/create-self-service-experiences/setup-backend/github-workflow/examples/Jira/report-a-bug.md`)
- Add tags to …
=> PORT-7790 | Update GitHub actions for SonarQube, Jira and Datadog

docs/create-self-service-experiences/setup-backend/github-workflow/examples/argocd/sync-argocd-app.md
Update Self Service Guides for `Sync Argo CD App` github action following the new self service actions api
- Resource Path (`/create-self-service-experiences/setup-backend/github-workflow/examples/argocd/sync-argocd-app`)
=> PORT-7789 | Update Action Guide for Synchronizing an Argo CD Application

docs/build-your-software-catalog/sync-data-to-catalog/git/github/github.md
Removed a redundant empty bullet in Github Permissions
- Github (`/docs/build-your-software-catalog/sync-data-to-catalog/git/github/github.md`)
=> Remove redundant empty bullet

docs/create-self-service-experiences/set-self-service-actions-rbac/dynamic-permissions.md
This PR attempts to shed more light on the levers available to prospects and customers who want to configure dynamic permissions for their own self-service actions. The complete example provided is a great one, and I did the following to bolster this strong example:
- added comments in the JSON examples
- switched JSON comment formatting from `#` to `//` to improve readability
- refined the description in the opening `# Dynamic permissions` section
- rearranged the `### Guidelines` to be more prominent and give the user an earlier understanding of the primitives available to them in dynamic permissions
- provided an additional "potential use case"
- added a section called `### Breaking down the `conditions` query from the example permissions JSON`, which guides the user through the …
=> changes to dynamic permissions doc

docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/examples/cloud_resource/_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/examples/compute_resources/_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/examples/examples.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/examples/mapping_extra_resources.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/gcp.md
Following the change in mapping in the GCP Ocean integration, a realignment of the GCP mapping docs had to be changed. Now removing versioning from the resources + removal of the cloud resource kind 
- GCP (`/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/`)
- GCP examples (`/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/examples/`)
- Mapping extra resources (`/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/examples/mapping_extra_resources`)
=> [PORT-8328] [GCP] Aligned gcp docs with new removed versioned resources

docs/promote-scorecards/promote-scorecards.md, docs/search-and-query/search-and-query.md
Add missing search operators (`doesNotContains|endsWith|doesNotEndsWith|beginsWith|doesNotBeginsWith`)
- Search and Query (`/search-and-query/#operators`)
=> Update all search operators

docs/promote-scorecards/promote-scorecards.md
Fix a typo in the does not search / scorecard operator
- Promote Scorecards (`/promote-scorecards/promote-scorecards`)
=> Fix typo in doesNot operator

docs/guides-and-tutorials/scaffold-a-new-service.md
If copied and pasted, this backend example does not work due to two trailing commas. When removed, the backend works.
- docs/guides-and-tutorials/scaffold-a-new-service.md
=> Removing trailing commas from backend example

docs/guides-and-tutorials/scaffold-a-new-service.md
Described how to specify a private repo template when scaffolding a new service (GitHub only). Also added comments to help users understand what the GitLab pipeline is doing at each step.
- docs/guides-and-tutorials/scaffold-a-new-service.m
=> updating scaffold new service

docs/guides-and-tutorials/scaffold-a-new-service.md
- Changed line 19 to line 22 in GitHub backend setup
- Reminded user to ensure `.github/workflows` directory exists before creating pipeline file
- Changed the name of the button you need to click from "create" to "save" to reflect the UI accurately
- docs/guides-and-tutorials/scaffold-a-new-service.md
=> slight changes to scaffold new service instructions

docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples/mapping_extra_resources.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installation.md
- **Add `useGetResourceAPI` option to the AWS Lambda function mapping in the `mapping_extra_resources.md`.**
- **feat: add helm installation**
- **feat: add installation warnings**
- AWS Installation (/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installation)
- Mapping extra resources (/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples/mapping_extra_resources)
=> PORT 8756 aws integration add use get resource api to docs

docs/guides-and-tutorials/create-cloud-resource-using-iac.md
The link at the bottom of the _Create Cloud Resource Using IAC_ page pointing to the _Deploy AWS resources using AWS CloudFormation_ guide was broken. Link has been updated to point to the correct _Deploy AWS resources using AWS CloudFormation_ page. 
N/A
/docs/guides-and-tutorials/create-cloud-resource-using-iac.md
=> fixed broken cloudformation guide url in IaC guide

docs/actions-and-automations/setup-backend/github-workflow/examples/AWS/deploy-s3-bucket-crossplane.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/aws.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installations/_category_.json, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installations/installation.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installations/multi_account.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/multi_account.md
Added a documentation for enabling multi account support.
- Multi accounts in AWS (`/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/multi-accounts`)
=> Add multi account permissions

docs/build-your-software-catalog/custom-integration/iac/terraform/examples/import-and-manage-integration.md, docs/build-your-software-catalog/custom-integration/iac/terraform/terraform.md
Add a guide for managing an integration using Terraform, including how to import the state from an existing integration.
- Import and Manage an Integration (`/build-your-software-catalog/custom-integration/iac/terraform/examples/import-and-manage-integration`)
- Terraform (`/build-your-software-catalog/custom-integration/iac/terraform/terraform.md`) (added link to new guide above)
=> Add Terraform Import State guide

docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/datadog.md
We recently made some changes to the integration blueprint to match the correct data types. We also added a new kind for SLO history. These changes are applied here in the docs as well
docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/datadog.md
=> [Datadog] - update docs to reflect changes in integration

docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples/mapping_extra_resources.md
Typos and GCP leftovers for the AWS integration docs
- AWS - Mapping Extra Resources (`/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples/mapping_extra_resources`)
=> Typos and GCP leftovers for the AWS integration docs

docs/build-your-software-catalog/sync-data-to-catalog/feature-management/launchdarkly/launchdarkly.md, docs/guides-and-tutorials/let-developers-enrich-services-using-gitops.md
LaunchDarkly helm command had a weird indenting issue, and enrich service guide had trailing commas.
- docs/build-your-software-catalog/sync-data-to-catalog/feature-management/launchdarkly/launchdarkly.md
- docs/guides-and-tutorials/let-developers-enrich-services-using-gitops.md
=> fixed indenting in LD helm command

docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/datadog.md, docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace.md, docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/newrelic.md, docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/sentry.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installations/installation.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/installation.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/examples/project/_project.mdx, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/installation.md, docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk/snyk.md, docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md, docs/build-your-software-catalog/sync-data-to-catalog/event-processing/kafka.md, docs/build-your-software-catalog/sync-data-to-catalog/feature-management/launchdarkly/launchdarkly.md, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/installation.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/firehydrant.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/opsgenie.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/servicenow.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage.md, docs/build-your-software-catalog/sync-data-to-catalog/jenkins/jenkins.md, docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira/jira.md, docs/build-your-software-catalog/sync-data-to-catalog/project-management/linear/linear.md, docs/build-your-software-catalog/sync-data-to-catalog/terraform-cloud/terraform-cloud.md
I noticed that many of the helm commands in the installation examples had misaligned indentation. I believe this was due to the recent addition of `--set sendRawDataExamples=true`, so I think I fixed it everywhere.
Also fixed a visual big where `:::tip` showed instead of the green tip card (`build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/installation`) and fixed the spelling of "instance" (`build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace`)
- apm-alerting/datadog.md
- apm-alerting/dynatrace.md
- apm-alerting/newrelic.md
- apm-alerting/sentry.md
- cloud-cost/opencost.md
- cloud-providers/aws/installations/installation.md
- cloud-providers/azure/installation.md
- cloud-providers/gcp/examples/project/_project.mdx
- …
=> fixed helm indentation and a few other things

docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installations/multi_account.md
Hide multi-account installation in AWS since there is a mistake over there
- Multi Account Installation (`/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installations/multi-account `)
=> fix: hide multi_account page

docs/build-your-software-catalog/sync-data-to-catalog/argocd/argocd.md
This PR removes duplicate `token` word in `integration.secrets.token` property description.
- ArgoCD (`docs/build-your-software-catalog/sync-data-to-catalog/argocd/argocd.md`)
=> Remove duplicate word "token" in argocd.md

docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/advanced.md
This PR fixes a typo `detremines` to `determines`.
- Advanced (`docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/advanced.md`)
=> Fix typo detremines -> determines

docs/guides-and-tutorials/let-developers-enrich-services-using-gitops.md
Small text change to `/guides-and-tutorials/let-developers-enrich-services-using-gitops/`
=> Text fix in Gitops guide

docs/build-your-software-catalog/sync-data-to-catalog/git/github/self-hosted-installation.md
Fix Github Self Hosted installation guide
- Github Self Hosted Installation (`/build-your-software-catalog/sync-data-to-catalog/git/github/self-hosted-installation.md`)
=> Fix github self hosted docs

docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/example-file/_gitlab_exporter_example_package_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/example-file/_gitlab_exporter_example_package_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/examples.md, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/gitlab.md
This PR adds docs on how to ingest files from your GitLab to Port to using the [GitLab file kind feature](https://github.com/port-labs/ocean/pull/891)
docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/gitlab.md
docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/examples.md
=> Documentation on ingesting GitLab file contents

docs/actions-and-automations/setup-backend/github-workflow/examples/Azure/tag-azure-resource.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installations/installation.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/installation.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/_create-service-account-and-key.mdx, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/installation.md
Updated the terraform version being referred to in the docs to a higher version
/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/installation?installation-methods=terraform
/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installations?installation-methods=terraform
/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/installation?installation-methods=terraform
=> PORT-9822|-Bug-Integrations docs use the wrong version of Terraform

docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/datadog.md
This pull request enhances the documentation for the Datadog integration by adding information about [the new `serviceMetric` resource](https://github.com/port-labs/ocean/pull/867). This resource allows users to fetch specific metrics from Datadog using a variety of filters, providing more flexibility and control over the data ingested into Port.
- **New Section on `serviceMetric` Resource**: A new section is added to the Datadog integration documentation, explaining the purpose and usage of the `serviceMetric` resource.
- **Configuration Examples**: Clear configuration examples are provided, demonstrating how to use the `datadogSelector` to filter metrics based on `metric`, `env`, `service`, and `timeframe`.
- **Explanation of Mapping**: The mapping between the Datadog response and the …
=> Enhance Datadog Integration Docs: Add serviceMetric Resource

docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/installation.md
1. Switched Terraform module our customers are being directed to by the docs
2. Changed the command
3. Added section for possible configurations for the provider
- (GCP) Installation (`/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/installation?installation-platforms=terraform`)
=> Updated GCP Terraform module's Installation method

docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installations/multi_account.md
- AWS Multi-account (`build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installations/multi_account`)
=> fix: add read only permissions to the integration account

docs/actions-and-automations/define-automations/define-automations.md, docs/actions-and-automations/define-automations/setup-action.md, docs/actions-and-automations/define-automations/setup-trigger.md
Headers in Automation docs could be clearer to avoid confusion, I've specified for each page what part of the action JSON we are talking about.
- Define Automations (`/actions-and-automations/define-automations/`)
- Setup trigger (`/actions-and-automations/define-automations/setup-trigger`)
- Setup backend (`/actions-and-automations/define-automations/setup-action`)
=> Clarifying Action JSON Headers

docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/_github_exporter_example_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/_github_exporter_example_pull_request_blueprint.mdx
The lead time property was originally set as a calculated field based on other properties like `createdAt` and `mergedAt`. However, since this calculation was performed dynamically ('on the fly'), it couldn't be mirrored as a predefined property. Upon further investigation, we realized that both `createdAt` and `mergedAt` are already available in the API response. As a result, there is no need to compute lead time as a calculated property. We've updated the blueprint and mapping configuration to directly ingest these values from the API, removing the need for on-the-fly calculations.
-  Resource mapping …
=> Update Github Pull Request Blueprint for Lead time in hours calculation

docs/guides/all/connect-github-codeowners-with-service-team-and-user.md
The mapping referenced a `Component` blueprint which is does not exist, I have updated this to point to the right blueprint `githubCodeowners`
- Blueprint (`docs/guides/all/connect-github-codeowners-with-service-team-and-user.md`)
=> Fixed incorrect blueprint in mapping in connect GitHub CODEOWNERS with Service, Team & User guide

docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/_azuredevops_exporter_supported_resources.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/example-board/_azuredevops_exporter_example_board_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/example-board/_azuredevops_exporter_example_board_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/examples.md, docs/guides/all/setup-dora-metrics.md
This PR adds support for Azure DevOps Boards in the Azure DevOps integration documentation, including new examples and configurations.
- Azure DevOps Board Blueprint Example (`/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/example-board/_azuredevops_exporter_example_board_blueprint.mdx`)
- Azure DevOps Board Port App Configuration Example (`/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/example-board/_azuredevops_exporter_example_board_port_app_config.mdx`)
- Azure DevOps Exporter Supported Resources (`/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/_azuredevops_exporter_supported_resources.mdx`)
- Azure DevOps Examples (`/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/examples.md`)
This PR adds documentation …
=> Port 10849 documentation for azure devops boards

docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/_github_exporter_example_pull_request_blueprint.mdx
using `.properties.updatedAt` to calculate the days old. This property represents the last time the PR was updated, not when it was created. To calculate the total number of days the PR has been open, you should use `.properties.createdAt`.
- Mapping Examples (`/build-your-software-catalog/sync-data-to-catalog/git/github/examples/resource-mapping-examples#map-repositories-and-pull-requests`)
=> PORT-10939 Incorrect property name in documentation for data sync to catalog.

docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/_azuredevops_exporter_supported_resources.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/example-release/_azuredevops_exporter_example_release_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/example-release/_azuredevops_exporter_example_release_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/examples.md
This change adds documentation for mapping Azure DevOps Release resources within Port's Azure DevOps integration. 
- **Azure DevOps Release Example Blueprint**  
Path: `/docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/example-release/_azuredevops_exporter_example_release_blueprint.mdx`
- **Azure DevOps Release Example Port App Config**  
Path: `/docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/example-release/_azuredevops_exporter_example_release_port_app_config.mdx`
- **Azure DevOps Examples**  
Path: `/docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/examples.md`  
Changes:  
- Added a new section for mapping Azure DevOps releases.
- Referenced the new blueprint and configuration example pages.
- Linked to the Azure …
=> Port 11112 azure devops releases

docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/example-project/_azuredevops_exporter_example_work_item_port_app_config.mdx
Updated the relationship in the work-item mapping in the ADO docs to use project ID to for relation to project. This harmonizes the docs with the integration defaults
- work-item mapping (`/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/examples`)
=> Updated project relation in work-item example mapping in ADO

docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/example-project/_azuredevops_exporter_example_work_item_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/example-project/_azuredevops_exporter_example_work_item_port_app_config.mdx
Added the `assignedTo` field to the Azure DevOps work items integration docs.
N/A
- Azure DevOps Work Item Blueprint (`/integrations/azure-devops/example-project/_azuredevops_exporter_example_work_item_blueprint.mdx`)
- Added `assignedTo` property to schema.
- Azure DevOps Integration Configuration (`/integrations/azure-devops/example-project/_azuredevops_exporter_example_work_item_port_app_config.mdx`) 
- Added `assignedTo` mapping using System.AssignedTo.displayName field
=> Adds assigned to to the ADO work_items blueprint and kind config

docs/actions-and-automations/setup-backend/webhook/webhook.md
The Port API link referenced `localhost:4001`
- ...
- ...
=> broken link to port API

docs/guides/all/humanitec-integration.md
instructions reference `client` directory, however this leads to an error 
- ...
- ...
=> folder name incorrect in instructions

docs/guides/all/humanitec-integration.md
The ResourceGraph blueprint must be installed prior to the Resource blueprint, as it is referenced by it.
- ...
- ...
=> must install ResourceGraph before Resource blueprint

docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/datadog/example.md
Updates the documentation for the SLO History selector configuration to accurately reflect the current implementation, including correct default values, valid ranges, and clearer parameter descriptions. This ensures users can properly configure their SLO history collection based on the actual code implementation.
N/A
- Datadog APM Examples (`/build-your-software-catalog/sync-data-to-catalog/apm-alerting/datadog/example`)
Updates the documentation for the SLO History selector configuration to accurately reflect the current implementation, including:
- Correct default values
- Valid ranges for configuration options
- Clear descriptions of what each parameter controls
- Updated `timeframe` documentation to clarify it controls the time window for each data point
- Updated …
=> [Datadog] Update SLO History selector configuration documentation

docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/kubecost/kubecost.md
Restructured Kubecost integration guides to conform with the new docs template structure
Kubecost (`/build-your-software-catalog/sync-data-to-catalog/cloud-cost/kubecost/`)
=> PORT-11596 Kubecost Integration guide refactoring

docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/kubecost/kubecost.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost.md
Restructured opencost integration guide to conform to new docs structure
Opencost (`/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost`)
=> PORT-11597 OpenCost Integration guide refactoring

docs/build-your-software-catalog/sync-data-to-catalog/other/backstage.md
- Restructured Backstage integration guide to conform to new structure
Backstage (`/build-your-software-catalog/sync-data-to-catalog/other/backstage`)
=> PORT-11599 Backstage Integration guide refactoring

docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/datadog/datadog.md, docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace/dynatrace.md, docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/newrelic.md, docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/sentry.md, docs/build-your-software-catalog/sync-data-to-catalog/argocd/argocd.md, docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/octopus-deploy.md, docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk/snyk.md, docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/sonarqube.md, docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md, docs/build-your-software-catalog/sync-data-to-catalog/feature-management/launchdarkly/launchdarkly.md, docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/installation.md, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/installation.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/firehydrant.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/opsgenie/opsgenie.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty/pagerduty.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage/statuspage.md, docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira/jira.md, docs/build-your-software-catalog/sync-data-to-catalog/project-management/linear/linear.md, docs/build-your-software-catalog/sync-data-to-catalog/terraform-cloud/terraform-cloud.md, docs/generalTemplates/_integration_template.md
The headers of the installation types for the tabs in the integrations guide has changed to Real-time (self-hosted)
The scheduled tab (CI) references the old link to the real time and always on tab. The link has been changed to reflect the new one in all the integration guides 
Integration Docs (`/build-your-software-catalog/sync-data-to-catalog/`)
=> PORT-11787 Updating the real-time-updates section in the Scheduled CI for all integrations

docs/guides/all/pull-request-metrics.md
Added deprecation title to the old pr metrics guide. We still want to keep this guide but add a deprecation warning so that anyone who reviews it knows that it's deprecated
Old Pr Metrics guide page (`/guides/all/pull-request-metrics/#create-github-workflow`)
=> PORT-11708 Bug | Deprecate the old metrics guide

docs/api-reference/get-actions-automations.api.mdx, src/components/guides-section/consts.js, static/apispec.yaml
=> update publish param, add dependabot guide to appsec category

docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/installation.md
Added cloud run size for gcp integration tf module
- GCP installation (`/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/installation`)
=> [gcp] Added configurations

docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira/examples/_jira_example_issue_configuration.mdx, docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira/examples/_jira_issue_example_entity.mdx
Change issue priority from `id` to `name` to provide a better readable experience.
- Jira (`/build-your-software-catalog/sync-data-to-catalog/project-management/jira/`)
Integration PR: https://github.com/port-labs/ocean/pull/1267
=> Change issue priority from `id` to `name`

docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/resource_templates/subscription/_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/resource_templates/subscription/_subscription_blueprint.mdx
Aligning the default blueprint to the tags addition, based on the Ocean [repo](https://github.com/port-labs/ocean/blob/main/integrations/azure/.port/resources/port-app-config.yaml).
- Azure resources examples
=> Add Azure subscription tags to docs

docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/_gitlab_exporter_example_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/_gitlab_exporter_example_repository_blueprint.mdx
This PR updates the service blueprint and config mapping in the gitlab documentation to include project labels
- GitLab Exporter Example Port App Config (`/docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/_gitlab_exporter_example_port_app_config`)  
- GitLab Exporter Example Repository Blueprint (`/docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/_gitlab_exporter_example_repository_blueprint`)
=> Add support for GitLab repository labels

docs/build-your-software-catalog/sync-data-to-catalog/event-processing/kafka.md
The Kafka consumer group blueprint currently expects members to be an array of strings. However, in the mapping configuration, the entire members object was being mapped, resulting in an error: `"members/0" must be string`. This occurs when users attempt to set up the integration using the mapping and configuration provided in the documentation.  
The updated documentation can be found at the following path:  
- **Kafka Integration**: `build-your-software-catalog/sync-data-to-catalog/event-processing/kafka`  
This update ensures the configuration and mapping align correctly with the blueprint requirements, resolving the issue for users.
=> Map Kafka members mapping to an array of client id strings

docs/guides/all/ingest-checkmarx-kics-scan-into-your-catalog.md
The KICS mapping was incorrect - looked like it was copied from Trivy. This config properly maps the fields from KICS results.json file to the blueprint in the guide.
Reviewed KICS instructions earlier today with Checkmarx team and KICS PM and we noticed some issues in the mapping config. As part of becoming "official" integration with Checkmarx we need to get the basic integration working so I've edited it to correct mappings.
- ...
- ...
=> Fix KICS mapping configuration

docs/guides/all/trigger-datadog-incident.md
Removed redundant publish field from Datadog incident trigger configuration
- Triggar DataDog Incident (`/guides/all/trigger-datadog-incident`)
=> PORT-12907 Removed publish key on trigger data dog incident SSA

docs/actions-and-automations/create-self-service-experiences/set-self-service-actions-rbac/dynamic-permissions.md
Clarify dynamic permissions section in self-service actions documentation
- Dynamic Permission page (`/actions-and-automations/create-self-service-experiences/set-self-service-actions-rbac/dynamic-permissions/`)
=> PORT-12912 Incorrect Documentation for Dynamic Permissions Logic

docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/advanced.md
we added support in bitbucket app to create missing related entities
- ...
- ...
=> added new tad for create missing related entities in bitbucket

docs/guides/all/scaffold-a-new-service.md
Changed the service to gitlab relation identifier to `git_lab_repositry`
- Scaffold new Guide (`/guides/all/scaffold-a-new-service?git-provider=gitlab`)
=> PORT-13086 | Fix Service - Gitlab relationship Identifier in scaffold new guide and other places in the documentation

docs/sso-rbac/sso-providers/oidc/azure-ad.md
The `groups claim` section does not seem to be relevant anymore, since the section it linked no longer exists on the page. The other similar section instructs the user to add additional permissions not `group claim`. Removing the info block with refers the non-existant section and updated the permission section with info about importing groups.
- How to configure AzureAD (`sso-rbac/sso-providers/oidc/azure-ad.md`)
We're applying this now to see whether the groups are pulled in as expected with just the `Directory.Read.All` permission or whether there is an actual section on `groups claim` missing in the docs.
=> Update broken section reference in azure-ad.md 

docs/guides/all/setup-slack-reminders.md
the current guide resulting an error, upgrading the port-sender version from 0.2.3 to 0.2.14 resolves it.
https://docs.port.io/guides/all/setup-slack-reminders
=> Fix port-sender version in slack-reminder self service action doc (bug fix)

docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples/mapping_extra_resources.md
Replaced AWS CLI documentation with Cloud Control API documentation
- Mapping Extra Resources
(`/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples/mapping_extra_resources/#usegetresourceapi-property-support `)
- ...
=> feat: replace cloud control api links with the API docs

docs/build-your-software-catalog/custom-integration/webhook/examples/bitbucket-server/_category_.json, docs/build-your-software-catalog/custom-integration/webhook/examples/bitbucket-server/bitbucket-server.md, docs/build-your-software-catalog/custom-integration/webhook/examples/bitbucket-server/gitops.md, docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/bitbucket.md, docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/gitops/gitops.md, docs/integrations-index.md
Add Bitbucket (Self-Hosted) webhook integration gitops for bitbucket
- Bitbucket (Self-hosted) Gitops (`/build-your-software-catalog/custom-integration/webhook/examples/bitbucket-server/gitops`)
- Bitbucket Server (`/build-your-software-catalog/custom-integration/webhook/examples/bitbucket-server/`)
=> PORT-13363-bug-it-is-not-mentioned-in-the-docs-that-we-support-gitops-in-self-hosted-bitbucket

docs/build-your-software-catalog/custom-integration/iac/terraform/_terraform_provider_base.mdx
The version mentioned in the docs is more than 3 months old with many new feature missing (2.0.X vs 2.4.Y)
N/A
- [Terraform - Installation](https://docs.port.io/build-your-software-catalog/custom-integration/iac/terraform/#installation)
=> Update our Terraform provider version to latest minor

docs/sso-rbac/rbac/as-blueprints.md
Update jqQuery in RBAC documentation to use teamsIdentifiers
Non-working: [.user.team] (doesn't work because it doesn't properly access the team data) Working but not optimal: 
[.user.team[]] (works but doesn't take full advantage of the new structure) 
Optimal  approach:".user.team"It's simpler and more readable
It does exactly what we need without any extra complexity
- As blueprint (New)(`/sso-rbac/rbac/as-blueprints/#self-service-actions`)
=> PORT-13370-bug-the-example-should-be-updated-to-the-new-users-and-teams-version

docs/sso-rbac/sso-providers/saml/okta.md
Update Okta SAML documentation for clarity and add user deprovisioning info
- How to configure Okta (`/sso-rbac/sso-providers/saml/okta#scim-configuration-beta`)
=> PORT-13415-bug-to-mention-that-user-deprovisioning-in-okta-saml-scim-is-not-visually-displayed-on-ports-ui

docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/installation.md
Added a tooltip indicating that you can use alternative permissions model for gitlab at your own risk.
- gitlab installation (`/build-your-software-catalog/sync-data-to-catalog/git/gitlab/installation`)
=> Added permissions tip in gitlab

docs/guides/all/trigger-firehydrant-incident.md, src/components/guides-section/consts.js
Added a guide for triggering FireHydrant incident from show and tell
a Self-Service action that allows you to trigger a FireHydrant incident directly from Port.
It streamlines the incident creation process and is easy to configure.
Trigger Firehydrant incident (`/guides/all/trigger-firehydrant-incident`)
=> PORT-13719-from-show-and-tell-create-a-self-service-action-that-allows-you-to-trigger-a-fire-hydrant-incident

docs/guides/all/visualize-service-argocd-runtime.md
Update ArgoCD integration mapping configuration and improve documentation clarity
- Visualize your services' Kubernetes runtime using ArgoCD (`/guides/all/visualize-service-argocd-runtime#what-does-the-integration-do`)
=> PORT-13808 Refactor mapping configuration in the automatic dicovery

docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/sonarqube.md
Added Optional for webhook secret
- ...
- ...
=> Remove webhook secret hint from warning

src/components/ocean-saas-specifics/limitations.jsx, src/components/ocean-saas-specifics/live-events.jsx
Removed the default limitation for SaaS Ocean integration about resync times
- Ocean SaaS integrations
=> Removed ttl limitation from Ocean SaaS

docs/generalTemplates/_sso_auth0_endpoints.md, docs/generalTemplates/_sso_direct_url.md
In SSO docs, the US OIDC link was incorrect
- Endpoints (`/generalTemplates/_sso_auth0_endpoints.md`)
- Direct URL (`docs/generalTemplates/_sso_direct_url.md`)
=> Port 14084 us OIDC url

docs/guides/all/create-cloud-resource-using-iac.md
Changed the workflow in the guide.
Since the repository mapping is .full_name, the repo identifier shouldn't be :
${{ github.repository_owner }}/${{ fromJson(inputs.port_context).entity }} -> aka org-name/org-name/repo-name
but just: 
${{ fromJson(inputs.port_context).entity }} -> aka org-name/repo-name
- https://docs.port.io/guides/all/create-cloud-resource-using-iac/
=> Fix cloud resource workflow

docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab-v2/GitLab-v2.md, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab-v2/_category_.json, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab-v2/example-groups/_gitlab_integration_example_group_members_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab-v2/installation.md
Updated GitLab v2 integration docs:
- Changed blueprint from `gitlabGroupWithMember` to `gitlabGroup` in group members config.
- Added "Hosted by Port" the default tab in installation guide and replaced live events section with a webhook update note.
- None
- Group Members Config (`/build-your-software-catalog/sync-data-to-catalog/git/gitlab-v2/example-groups/_gitlab_integration_example_group_members_config.mdx`)
- Installation Guide (`/build-your-software-catalog/sync-data-to-catalog/git/gitlab-v2/installation.md`)
=> Update GitLab v2 , Bump to GA

docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/datadog/examples.md
This PR updates datadog teams mapping relation to generate an array o members correctly
- None
- Datadog example (`/build-your-software-catalog/sync-data-to-catalog/apm-alerting/datadog/examples/#team`)
=> PORT-14247 Updated datadog teams mapping relation to generate an array

docs/guides/all/trigger-servicenow-incident.md
The WEBHOOK action configuration does not support `username` and `password` keys. This PR fixes it by encoding the username and password as base64 secrets
- ...
- ...
=> Fix Authentication Bug in Trigger SNOW Guide

docs/guides/all/create-github-secret.md
valid secret names never meet regex requirement from doc.
- ...
- ...
=> fix incorrect regex from example

docs/build-your-software-catalog/customize-integrations/configure-data-model/relate-blueprints/relate-blueprints.md
Fixed the links that didn't work.
This is the relevant bug report: https://getport.atlassian.net/browse/PORT-14273
- https://docs.port.io/build-your-software-catalog/customize-integrations/configure-data-model/relate-blueprints/
=> fixed broken links

docs/actions-and-automations/define-automations/setup-trigger.md
Enhance automation trigger documentation with related entity deletion scenario and example. Clarified that automations will not trigger when a related entity is deleted or when a mirror property changes.
- Setup triggers (`/actions-and-automations/define-automations/setup-trigger`)
=> PORT-14793 Bug | To mention that Port Automations will not trigger upon deleting related entities

docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab-v2/examples.md
This PR updates the GitLab merge request configuration documentation to accurately reflect the implementation of the `states` and `updatedAfter` parameters. The changes include:
- Added "Merge Request Configuration Options" section
- Added clear documentation about the allowed values for the newly introduced`states` and `updatedAfter` merge request selectors.
- Clarified that `updatedAfter` only affects non-opened merge requests
- Added proper section header for configuration options
- GitLab v2 Examples (`/build-your-software-catalog/sync-data-to-catalog/git/gitlab-v2/examples.md`)
=> Add Merge Request Configuration Options

src/components/guides-section/consts.js
Remove PagerDuty incident management guide from available guides list to prevent duplication
Const file updated
- ...
- ...
=> Remove PagerDuty incident management guide from available guides list

docs/build-your-software-catalog/custom-integration/iac/terraform/terraform.md
Updated the Terraform documentation to include instructions for importing existing webhooks and integrations. Added new resource examples and commands for managing these entities in the Terraform state.
- Terraform (`/build-your-software-catalog/custom-integration/iac/terraform/?property=yaml&current-scenario=integration#import-existing-data-to-the-terraform-state`)
=> PORT-12291 Add support for importing webhooks and integrations in Terraform documentation

docs/customize-pages-dashboards-and-plugins/dashboards/dashboards.md
inside markdown widget, the iframe tag and the video tag don't support external video urls like a youtube video url.
There was a bug opened about this but we don't want to allow it, so adding it explicitly in the docs, that it is allowed in the iframe.
Bug opened because of that: [14910](https://getport.atlassian.net/browse/PORT-14910)
Slack thread talking about not allowing this: https://getport.slack.com/archives/C06DQ1QR35L/p1750678475428669
- docs/customize-pages-dashboards-and-plugins/dashboards/dashboards.md
=> add note of limitation on external video urls

docs/guides/all/import-and-manage-integration.md
Update Terraform integration guide to clarify usage of Import State feature and prerequisites
- Manage integration mapping using Terraform (`/guides/all/import-and-manage-integration`)
=> Bug | PORT-15315 Kubernetes integration is not mandatory in the terraform management guide

docs/guides/all/add-rca-context-to-ai-agents.md, src/components/guides-section/consts.js
Renamed guide on adding context to AI agents and update references to reflect the new focus on Root Cause Analysis (RCA) context business use case
- Add RCA context to AI agents (`/guides/all/add-rca-context-to-ai-agents`)
=> Bug | PORT-15338  Rename the Add context to AI Agents guide to a more business use case title for RCA

docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab-v2/gitops/gitops.md
Clarify baseUrl requirement for self-hosted GitLab integration
- Updated the admonition in the GitLab GitOps docs to specify that the `baseUrl` parameter is required only for self-hosted integrations.
- Improves clarity for users setting up GitOps with GitLab.
- `/build-your-software-catalog/sync-data-to-catalog/git/gitlab-v2/gitops/gitops`
=> Clarify baseUrl requirement for self-hosted GitLab integration in GitOps docs

docs/actions-and-automations/create-self-service-experiences/setup-ui-for-action/advanced-form-configurations.md, docs/sso-rbac/sso-providers/oidc/azure-ad.md, docs/sso-rbac/sso-providers/oidc/okta.md, docs/sso-rbac/sso-providers/oidc/onelogin.md, docs/sso-rbac/sso-providers/saml/azure-ad.md, docs/sso-rbac/sso-providers/saml/google-workspace.md, docs/sso-rbac/sso-providers/saml/jumpcloud.md, docs/sso-rbac/sso-providers/saml/okta.md
=> update sso titles, add empty string note

docs/customize-pages-dashboards-and-plugins/dashboards/dashboards.md
As per this JIRA issue: https://getport.atlassian.net/browse/PORT-15626
I deleted the 'svg' from the supported html tags
- https://docs.port.io/customize-pages-dashboards-and-plugins/dashboards/#markdown
=> deleted svg from the supported html tags

docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk/snyk.md
New Relic investigation on Snyk shows a lot of 401 unauthorized errors, my investigations shows this is likely due to customers attempting to install the integration with non-enterprise Snyk accounts where the API is not available, this clarifies that a Snyk enterprise account is necessary, along with relevant link.
- Snyk (`/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk/`)
=> Add a prerequisite to Snyk docs

docs/actions-and-automations/define-automations/setup-trigger.md
Added automation action identifiers section to setup-trigger documentation to clarify that automations can be triggered by other automations.
- Set up trigger(`/actions-and-automations/define-automations/setup-trigger`)
=> PORT-15871 Add automation action identifiers section to setup-trigger documentation

docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab-v2/GitLab-v2.md, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/migration.md
This PR updates the GitLab v2 integration documentation to clarify file path pattern differences between v1 and v2 versions. The changes address user confusion around the migration from GitLab v1's glob patterns to GitLab v2's Advanced Search API syntax, which has more limited wildcard support.
No new docs pages were added.
- GitLab v2 integration (`/build-your-software-catalog/sync-data-to-catalog/git/gitlab-v2/GitLab-v2`)
- GitLab migration guide (`/build-your-software-catalog/sync-data-to-catalog/git/gitlab/migration`)
- Updated package.json path examples from `**/package.json` to `package.json` to reflect v2's simpler path syntax
- Added caution note explaining GitLab-v2's path search limitations and differences from v1
- Added migration pattern comparison table with specific examples …
=> Update GitLab v2 path config patterns and add migration comparison table

docs/guides/all/visualize-service-k8s-runtime.md
Fix broken indentation in deployment.yaml example in visualize-service-k8s-runtime.md
- Visualize your services' k8s runtime (`guides/all/visualize-service-k8s-runtime`)
=> Fix broken indentation in deployment.yaml example

docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/azure-devops.md, docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/mapping_extensions.md
Added Documention for selector configuration to include repository information for pipelines, enabling direct pipeline→repository relationships.
Needed for cases where repo-level linkage is required; disabled by default due to extra API calls and potential rate limit impact.
/docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/azure-devops
- ...
/docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/azure-devops
- ...
=> Fix Azure DevOps Documentation for Pipeline and Repository Relationship

docs/build-your-software-catalog/sync-data-to-catalog/sync-data-to-catalog.md
Added the note of not recommending OAuth for production enviroments.
- https://docs.port.io/build-your-software-catalog/sync-data-to-catalog/#installation-methods
=> Added OAuth note about prod environments

docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/bitbucket-server/bitbucket-server.md
Fixed issue where pull requests in the Bitbucket Server integration were not unique across multiple repositories during data ingestion.
- ...
docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/bitbucket-server/bitbucket-server.md
- ...
=> Improve identifier mapping logic for Bitbucket Server integration

docs/build-your-software-catalog/set-catalog-rbac/examples.md
Replace team inheritance with inherited ownership in the examples
- /build-your-software-catalog/set-catalog-rbac/examples#team-examples
=> fix team inheritance example

docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/_azure_docker_params.mdx, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/installation.md
Added a tab for the gitlab CI integration with Azure.
- https://docs.port.io/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/installation?installation-methods=ci#installation-methods
=> Portn 3647 add gitlab to azure installation

docs/search-and-query/global-search.md
Added a documentation that blueprints and actions can be searched in the global search bar.
- https://docs.port.io/search-and-query/global-search#search-results
=> Added actions and blueprints to the global search

docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab-v2/GitLab-v2.md
Handled the following JIRA issue: https://getport.atlassian.net/browse/PORT-16339
In the default mapping given for GitLab V2, under the project kind, changed the blueprint identifier from service to gitlabRepository.
- https://docs.port.io/build-your-software-catalog/sync-data-to-catalog/git/gitlab-v2/#default-mapping-configuration
=> change the default mapping of gitlab-v2 to gitlabRepository from service

docs/guides/all/trigger-github-copilot-from-port.md
Update GitHub integration mapping to include new `githubIssue` blueprint for issue synchronization
- None
- Trigger GitHub Copilot from Port - (`/guides/all/trigger-github-copilot-from-port#update-github-integration-mapping`)
=> Added the github issue mapping configuration to the trigger copilot guide

docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/properties/properties.md, docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/setup-blueprint.md
Added limitations to the identifier of blueprints and property.
=> Added limitations to blueprint and property identifiers

docs/guides/all/trigger-github-copilot-from-port.md
Updated the SSA to have the auto assign to copilot toggler and modified the backend to handle defaults in the workload
- None
- Trigger GitHub Copilot from Port (`/guides/all/trigger-github-copilot-from-port`)
=> Add auto-assign feature for GitHub Copilot in issue creation

docs/guides/all/self-heal-scorecards-with-ai.md
Added Track AI driven PR as prerequisite to self healing scorecard guide
- None
- Auto-fix services when scorecards degrade - (`/guides/all/self-heal-scorecards-with-ai/`)
=> Add track ai driven guide link to prerequisite in self healing scorcard guide
