docs/tutorials/entity-basics.md
Make some updates to upsert and merge behavior explanations
- Entity Basics (`/tutorials/entity-basics`)
=> PORT-2039 Update merge and upsert section

docs/software-catalog/search-in-port.md
- Search in Port (`/software-catalog/search-in-port`)
=> PORT-2119 Remove dependedOn operator references

docs/software-catalog/blueprint/calculation-properties.md
=> fixed type

docs/exporters/github-exporter/github-exporter.md
=> change cluster wording

docs/software-catalog/blueprint/calculation-properties.md
=> PORT-2120-improve-calculate-docs

.github/CODEOWNERS, docs/self-service-actions/action-runs-tutorial.md, docs/self-service-actions/self-service-actions-deep-dive.md
=> PORT-2227 Apply post CR changes

docs/software-catalog/relation/relation.md
- Relation (`/software-catalog/relation/`)
=> updated relation docs according to PORT-1765

__quickstart_old.md, docs/exporters/bitbucket-exporter/exporting-pull-requests.md, docs/exporters/bitbucket-exporter/exporting-repositories.md, docs/exporters/github-exporter/exporting-issues.md, docs/exporters/github-exporter/exporting-workflows-runs.md, docs/exporters/github-exporter/exporting-workflows.md, docs/quickstart.md, docs/self-service-actions/action-runs-tutorial.md
=> Remove formula properties from the docs

docs/self-service-actions/action-runs-tutorial.md, docs/self-service-actions/self-service-actions-deep-dive.md
=> PORT-2312 Make tiny fixes

docs/software-catalog/blueprint/blueprint.md
Added documentation for User format array
=> Added documentation for User format array

docs/exporters/bitbucket-exporter/bitbucket-exporter.md, docs/exporters/bitbucket-exporter/configuration.md, docs/exporters/bitbucket-exporter/exporting-pull-requests.md, docs/exporters/bitbucket-exporter/exporting-repositories.md, docs/exporters/bitbucket-exporter/installation.md
- Bitbucket Exporter Configuration (`/exporters/bitbucket-exporter/configuration.md`)
=> Add configuration page to bitbucket app

docs/exporters/bitbucket-exporter/exporting-pull-requests.md, docs/exporters/bitbucket-exporter/exporting-repositories.md, docs/exporters/github-exporter/exporting-pull-requests.md, docs/exporters/github-exporter/exporting-repositories.md, docs/exporters/github-exporter/self-hosted-installation.md, docs/software-catalog/scorecard/scorecard.md
Added improvement for the docs in the following areas:
- Scorecard
- Bitbucket Exporter
- GitHub Exporter
=> added docs improvements

docs/quickstart.md
=> PORT-2382 Remove unnecessary note from quickstart

docs/software-catalog/entity/tutorial.md
Docs about how to remove the relation
- remove-relations (`/software-catalog/entity/tutorial#remove-relations`)
=> PORT-2362 Relation delete docs

docs/software-catalog/blueprint/blueprint.md
=> PORT-2439 Small fixes

docs/software-catalog/scorecard/scorecard.md
Improvements to scorecard docs
- Quickstart (`/scorecard/scorecard.md`)
=> more improvement to scorecard docs

CONTRIBUTING.md, docs/api-providers/gitops/github-app-gitops/auto-importing-properties.md, docs/complete-use-cases/package-dependency-mapping.md, docs/complete-use-cases/sdlc.md, docs/complete-use-cases/service-locking.md, docs/exporters/bitbucket-exporter/exporting-pull-requests.md, docs/exporters/github-exporter/exporting-pull-requests.md, docs/exporters/github-exporter/exporting-workflows-runs.md, docs/exporters/k8s-exporter/quickstart.md, docs/self-service-actions/self-service-actions-deep-dive.md, docs/self-service-actions/webhook/examples/changelog-listener.md, docs/software-catalog/blueprint/blueprint.md, docs/software-catalog/blueprint/timer-properties.md, docs/software-catalog/blueprint/tutorial.md, docs/software-catalog/entity/entity.md, docs/software-catalog/entity/tutorial.md, docs/software-catalog/relation/relation.md, docs/software-catalog/relation/tutorial.md, docs/software-catalog/role-based-access-control/users-and-teams-management.md, docs/software-catalog/scorecard/tutorial.md, docs/software-catalog/search-in-port.md
=> PORT-2499 Update all identifiers in docs to match format

docs/software-catalog/widgets/async-api.md
=> Fix async api version

docusaurus.config.js
=> Add demo link to the docs

docs/api-providers/gitops/github-app-gitops/advanced-configuration.md
=> added a new flag to github gitops

docs/api-providers/github-action.md
=> added icon to gh-action

docs/self-service-actions/self-service-actions-deep-dive.md, docs/software-catalog/blueprint/blueprint.md
=> PORT-2719 Update icons

docs/api-providers/gitops/bitbucket-app-gitops/multiple-entities.md, docs/api-providers/gitops/github-app-gitops/multiple-entities.md, docs/software-catalog/page/tutorial.md
=> Small changes uppercase to lower

docs/software-catalog/page/tutorial.md
=> added some note

docs/complete-use-cases/full-kubernetes-exporter.md
=> Port 2532 docs https docs getport io complete use cases full kubernetes exporter

docs/single-sign-on/azure-ad.md, docs/single-sign-on/okta.md, docs/single-sign-on/onelogin.md
=> PORT-2780 Slight fixes to SSO docs

docs/self-service-actions/kafka/examples/changelog-basic-change-listener-using-aws-lambda.md, docs/self-service-actions/kafka/examples/execution-basic-runner-using-aws-lambda.md
=> PORT-2810 Add small note

docs/self-service-actions/action-runs-tutorial.md, docs/self-service-actions/kafka/examples/execution-basic-runner-using-aws-lambda.md, docs/self-service-actions/self-service-actions-deep-dive.md
=> added user infromation to docs

docs/self-service-actions/self-service-actions-deep-dive.md, docs/software-catalog/role-based-access-control/permissions-controls.md
=> Create docs about manual approval

docs/software-catalog/blueprint/blueprint.md, docs/software-catalog/blueprint/tutorial.md, package-lock.json, package.json
=> PORT-2813 Update docusaurus to 2.3.0

docs/build-your-software-catalog/sync-data-to-catalog/git-provider/bitbucket-exporter/exporting-pull-requests.md, docs/build-your-software-catalog/sync-data-to-catalog/git-provider/bitbucket-exporter/exporting-repositories.md
=> improvements

docs/build-your-software-catalog/search-and-query/_combinator_intro.md, docs/build-your-software-catalog/search-and-query/examples.md, docs/build-your-software-catalog/search-and-query/search-and-query.md, docs/build-your-software-catalog/sync-data-to-catalog/api/api.md, docs/build-your-software-catalog/sync-data-to-catalog/ci-cd/codefresh-workflow-template/codefresh-workflow-template.md, docs/build-your-software-catalog/sync-data-to-catalog/ci-cd/github-workflow/github-workflow.md, docs/build-your-software-catalog/sync-data-to-catalog/gitops/bitbucket-app-gitops/bitbucket-app-gitops.md
=> PORT-2934 Fix markup notes

docs/build-your-software-catalog/sync-data-to-catalog/ci-cd/github-workflow/examples.mdx, docs/build-your-software-catalog/sync-data-to-catalog/ci-cd/github-workflow/github-workflow.md
=> Add teams example in github action

docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/advanced.md
=> PORT-2973 small fixes

src/css/custom.css
=> Update lightmode code highlighting

src/css/custom.css
=> Fix lightmode color

docs/build-your-software-catalog/sync-data-to-catalog/api/api.md
=> PORT-2899 Add delete and delete-all api references

docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/mirror-property/mirror-property.md, docs/build-your-software-catalog/search-and-query/advanced.md, docs/build-your-software-catalog/set-catalog-rbac/examples.md, docs/build-your-software-catalog/sync-data-to-catalog/sync-data-to-catalog.md, docs/self-service-actions/kafka/examples/changelog-basic-change-listener-using-aws-lambda.md, docs/sso-rbac/rbac/rbac.md
=> PORT-2907 Add team inheritance docs

docs/build-your-software-catalog/search-and-query/search-and-query.md
=> Added rule of schema field search

docs/build-your-software-catalog/sync-data-to-catalog/gitops/github-app-gitops/advanced-configuration.md
=> Fixed link

docs/build-your-software-catalog/build-your-software-catalog.md, docs/build-your-software-catalog/sync-data-to-catalog/_category_.json, docs/build-your-software-catalog/sync-data-to-catalog/iac/terraform/terraform.md, docs/build-your-software-catalog/sync-data-to-catalog/sync-data-to-catalog.md, docs/configuration-methods/configuration-methods.md
=> PORT-3110 Change sync to ingest

docs/build-your-software-catalog/sync-data-to-catalog/aws/aws.md, docs/build-your-software-catalog/sync-data-to-catalog/aws/run-on-events.md
- AWS Exporter (`build-your-software-catalog/sync-data-to-catalog/aws/*`)
=> Change run-on-events header

docs/build-your-software-catalog/sync-data-to-catalog/aws/aws.md, docs/build-your-software-catalog/sync-data-to-catalog/git-provider/bitbucket-exporter/bitbucket-exporter.md, docs/build-your-software-catalog/sync-data-to-catalog/git-provider/git-provider.md, docs/build-your-software-catalog/sync-data-to-catalog/git-provider/github-exporter/github-exporter.md, docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/kubernetes.md
=> PORT-3069 Add real-time note

docs/self-service-actions/github-workflow/github-workflow.md
=> PORT-3055 add small note

docs/build-your-software-catalog/sync-data-to-catalog/gitops/github-app-gitops/advanced-configuration.md
=> Remove note from advanced configuration

docs/build-your-software-catalog/sync-data-to-catalog/aws/aws.md
=> PORT-3221 Fix wrong text

README.md
update docs URL in README
- ...
- ...
=> docs: update docs URL in README

docs/self-service-actions/self-service-actions-deep-dive/action-runs-tutorial.md
=> PORT-3204 Add action run logs docs

docs/sso-rbac/sso-providers/azure-ad.md
=> PORT-3236 Small fix in azure ad

docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/bitbucket.md, docs/build-your-software-catalog/sync-data-to-catalog/git/custom-gitops-integration.md, docs/build-your-software-catalog/sync-data-to-catalog/git/github/example-issue/_git_exporter_example_issue_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/example-issue/_github_exporter_example_issue_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/example-workflow-workflowrun/_git_exporter_example_workflow_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/example-workflow-workflowrun/_git_exporter_example_workflow_run_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/example-workflow-workflowrun/_github_exporter_example_wf_wfr_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples.md, docs/build-your-software-catalog/sync-data-to-catalog/git/github/github.md
=> PORT-3248 Bring back examples for issue and workflow

docs/build-your-software-catalog/build-your-software-catalog.md, docs/quickstart.md, docusaurus.config.js
=> Remove some ideal image usage

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/github.md, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/jira.md, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/opsgenie.md, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/opsgenie/_example_opsgenie_alert_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/opsgenie/_example_opsgenie_alert_configuration.mdx, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/sonarqube.md
=> Port-3302 generic webhook docs opsgenie

docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/timer.md
=> Fix timer docs

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/gitlab.md, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/gitlab/_example_gitlab_mr_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/gitlab/_example_gitlab_mr_configuration.mdx, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/sonarqube.md
=> Add gitlab example

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/github/_example_github_pr_configuration.mdx
=> Fixed webhook example

docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/mirror-property/mirror-property.md
=> Small text fix in mirror properties

docs/build-your-software-catalog/define-your-data-model/relate-blueprints/relate-blueprints.md, docs/build-your-software-catalog/sync-data-to-catalog/iac/terraform/_terraform_provider_base.mdx, docs/build-your-software-catalog/sync-data-to-catalog/iac/terraform/examples/_backstage-c4.md, docs/build-your-software-catalog/sync-data-to-catalog/iac/terraform/examples/create-dev-env.md, docs/build-your-software-catalog/sync-data-to-catalog/iac/terraform/examples/s3-bucket.md, docs/build-your-software-catalog/sync-data-to-catalog/iac/terraform/examples/terraform-managed-blueprint.md
=> PORT-3404 Add comprehensive blueprint example

docs/build-your-software-catalog/sync-data-to-catalog/iac/terraform/examples/terraform-managed-blueprint.md
=> PORT-3412 Update the terraform example

docs/build-your-software-catalog/define-your-data-model/relate-blueprints/relate-blueprints.md
=> Add warning about many TF relation

docs/build-your-software-catalog/build-your-software-catalog.md, docs/build-your-software-catalog/define-your-data-model/define-your-data-model.md, docs/build-your-software-catalog/define-your-data-model/relate-blueprints/relate-blueprints.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/setup-blueprint.md, docs/build-your-software-catalog/set-catalog-rbac/set-catalog-rbac.md, docs/build-your-software-catalog/sync-data-to-catalog/api/api.md, docs/build-your-software-catalog/sync-data-to-catalog/sync-data-to-catalog.md, docs/port-overview.md
=> PORT-3505 Embed loom videos from the software catalog section

docs/port-overview.md, docs/quickstart.md, docusaurus.config.js
=> PORT-3509 Make overview the root page

docs/build-your-software-catalog/build-your-software-catalog.md, docs/build-your-software-catalog/define-your-data-model/define-your-data-model.md, docs/build-your-software-catalog/define-your-data-model/relate-blueprints/relate-blueprints.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/setup-blueprint.md, docs/build-your-software-catalog/set-catalog-rbac/set-catalog-rbac.md, docs/build-your-software-catalog/sync-data-to-catalog/api/api.md, docs/build-your-software-catalog/sync-data-to-catalog/sync-data-to-catalog.md, docs/port-overview.md
=> PORT-3524 Update video embeds

docs/build-your-software-catalog/sync-data-to-catalog/iac/pulumi/pulumi.md, docs/build-your-software-catalog/sync-data-to-catalog/iac/terraform/terraform.md
=> PORT-3592 Add Pulumi backlink

docs/build-your-software-catalog/sync-data-to-catalog/api/api.md
=> PORT-3356 Update JS examples in docs

docs/create-self-service-experiences/setup-ui-for-action/setup-ui-for-action.md
=> PORT-3604 Add note about actions array

docs/api-reference/api-reference.mdx, docusaurus.config.js, package-lock.json, package.json
=> PORT-3625 Fix issue building docs

docs/create-self-service-experiences/setup-backend/azure-pipeline/azure-pipeline.md, docs/create-self-service-experiences/setup-backend/azure-pipeline/examples/examples.md
=> Fix azure devops type

docs/create-self-service-experiences/reflect-action-progress/reflect-action-progress.md
=> PORT-3701 Fix wrong payload example

docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/installation.md
=> Small terminology fix

docs/build-your-software-catalog/build-your-software-catalog.md, docs/build-your-software-catalog/define-your-data-model/define-your-data-model.md, docs/build-your-software-catalog/define-your-data-model/relate-blueprints/relate-blueprints.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/setup-blueprint.md, docs/build-your-software-catalog/set-catalog-rbac/set-catalog-rbac.md, docs/build-your-software-catalog/sync-data-to-catalog/api/api.md, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/installation.md, docs/build-your-software-catalog/sync-data-to-catalog/sync-data-to-catalog.md, docs/port-overview.md
=> PORT-3721 make video blocks smaller

docs/build-your-software-catalog/sync-data-to-catalog/gcp/examples/extended-specific-assets.md, docs/build-your-software-catalog/sync-data-to-catalog/gcp/examples/generic-assets.md
Extend GCP example to include organization, folders and all projects.
- GCP Examples (`/build-your-software-catalog/sync-data-to-catalog/gcp/examples`)
=> Extend GCP example to include organization, folders and all projects

docs/build-your-software-catalog/sync-data-to-catalog/gcp/examples/extended-specific-assets.md, docs/build-your-software-catalog/sync-data-to-catalog/gcp/examples/generic-assets.md, docs/build-your-software-catalog/sync-data-to-catalog/iac/terraform/examples/_backstage-c4.md, docs/build-your-software-catalog/sync-data-to-catalog/iac/terraform/examples/create-dev-env.md, docs/build-your-software-catalog/sync-data-to-catalog/iac/terraform/examples/s3-bucket.md, docs/build-your-software-catalog/sync-data-to-catalog/iac/terraform/examples/terraform-managed-blueprint.md
=> Update TF provider versions

docs/promote-scorecards/promote-scorecards.md
scorecard description docs
- ...
- ...
=> Port 3572 docs

docs/faq/faq.md
=> PORT-3927 Update self-hosted note in FAQ

docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples.md
=> Remove empty brackets

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/git/_category_.json, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/git/github.md, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/git/gitlab.md
=> Move gitlab and github locations

package-lock.json, package.json
=> PORT-3998 Update docusaurus version

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/go.md, docs/create-self-service-experiences/create-self-service-experiences.md, docs/port-overview.md
=> PORT-4034 Fix some typos and issues

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/pagerduty.md, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/jira/_example_jira_issue_blueprint.mdx
=> PORT-4042 Small fixes

docs/sso-rbac/sso-providers/azure-ad.md
=> PORT-4072 Update docs with app permissions

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/go.md
Include Python script to ingest Go dependency into Port.
- Quickstart (`/docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/go.md`)
- ...
=> Go python script

docs/build-your-software-catalog/sync-data-to-catalog/iac/terraform/examples/resource-scaffolding.md, docs/create-self-service-experiences/security/security.md
=> PORT-4110 Bring back IAC templates

docs/build-your-software-catalog/sync-data-to-catalog/iac/terraform/examples/no-code-resource-provisioning.md
=> PORT-4110 rename file and text

docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/_bitbucket_exporter_example_monorepo_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/_bitbucket_exporter_example_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/_github_exporter_example_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/example-issue/_github_exporter_example_issue_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/example-monorepo/_github_exporter_example_monorepo_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/example-workflow-workflowrun/_github_exporter_example_wf_wfr_port_app_config.mdx
=> changed property id to match the template

docs/build-your-software-catalog/set-catalog-rbac/set-catalog-rbac.md, docs/create-self-service-experiences/set-self-service-actions-rbac/set-self-service-actions-rbac.md, docs/customize-pages-dashboards-and-plugins/page/page-permissions.md, docs/customize-pages-dashboards-and-plugins/page/page.md
=> PORT-3745 Update pages to tutorial to page permissions

docs/customize-pages-dashboards-and-plugins/widgets/async-api.md, docs/customize-pages-dashboards-and-plugins/widgets/open-api.md
=> PORT-3672 Add note about S3 CORS

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/go.md, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/java.md, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/resources/java/_example_maven_bash.mdx, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/resources/java/_example_maven_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/resources/java/_example_maven_webhook_configuration.mdx
=> Add maven dependencies example

docs/sso-rbac/rbac/rbac.md, docs/sso-rbac/sso-rbac.md
=> PORT-4132 Add tip in global rbac section

docs/build-your-software-catalog/sync-data-to-catalog/aws/Installation.md
=> Added ec2 instance to terraform installation

docs/create-self-service-experiences/setup-backend/kafka/examples/changelog-basic-change-listener-using-aws-lambda.md, docs/create-self-service-experiences/setup-backend/kafka/examples/execution-basic-runner-using-aws-lambda.md
=> changed kafka urls in needed places

docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/array.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/boolean.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/calculation-property/calculation-property.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/datetime.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/email.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/mirror-property/mirror-property.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/number.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/object.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/string.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/team.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/timer.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/url.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/user.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/yaml.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/setup-blueprint.md, docs/build-your-software-catalog/sync-data-to-catalog/iac/pulumi/_pulumi_provider_base.mdx, docs/build-your-software-catalog/sync-data-to-catalog/iac/pulumi/examples/pulumi-managed-blueprint.md, docs/build-your-software-catalog/sync-data-to-catalog/iac/pulumi/pulumi.md
- Pulumi Base (`docs/build-your-software-catalog/sync-data-to-catalog/iac/pulumi/_pulumi_provider_base.mdx`)
- Example (`docs/build-your-software-catalog/sync-data-to-catalog/iac/pulumi/examples/pulumi-managed-blueprint.md`)
- Pulumi (`docs/build-your-software-catalog/sync-data-to-catalog/iac/pulumi/pulumi.md`
- And some other places (`docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/*`)
=> docs: update Pulumi docs to reflect new location of the provider

docs/create-self-service-experiences/setup-backend/kafka/examples/changelog-basic-change-listener-using-aws-lambda.md, docs/create-self-service-experiences/setup-backend/kafka/examples/execution-basic-runner-using-aws-lambda.md
=> Revert kafka brokers

docs/create-self-service-experiences/create-self-service-experiences.md, docs/create-self-service-experiences/setup-backend/setup-backend.md, docs/create-self-service-experiences/setup-ui-for-action/setup-ui-for-action.md
=> PORT-4190 Add new videos to the docs

docs/sso-rbac/sso-providers/azure-ad.md
=> changed note to prerequisite

docs/search-and-query/search-and-query.md, docusaurus.config.js
=> PORT-4263 Add search operators

docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/array.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/boolean.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/calculation-property/calculation-property.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/datetime.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/email.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/mirror-property/mirror-property.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/number.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/object.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/string.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/team.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/timer.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/url.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/user.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/yaml.md, docs/build-your-software-catalog/sync-data-to-catalog/iac/pulumi/_pulumi_provider_base.mdx, docs/build-your-software-catalog/sync-data-to-catalog/iac/pulumi/examples/pulumi-managed-blueprint.md, docs/build-your-software-catalog/sync-data-to-catalog/iac/pulumi/pulumi.md
=> docs: update Pulumi docs to reflect breaking changes

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/resources/soap/_example_python_script.mdx, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/resources/soap/_example_soap_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/resources/soap/_example_soap_webhook_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/soap.md
Added Python script, blueprint and webhook configuration to ingest a SOAP API file into Port
docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/resources/soap/
docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/soap.md
=> Ingest SOAP API File to Port

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/resources/sbom/_example_sbom_component_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/resources/sbom/_example_sbom_vulnerability_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/resources/sbom/_example_sbom_webhook_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/sbom.md
Ingested Software Bill of Materials (SBOM) components and vulnerabilities to Port
docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/resources/sbom/
docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/sbom.md
=> Add Software Bill of Materials (SBOM) to Port

docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/templates/argocd.md, docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/templates/full-kubernetes-exporter.md, docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/templates/istio.md, docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/templates/knative.md, docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/templates/openshift.md
=> finished docs

docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/templates/openshift.md
=> Added information for openshift docs

docs/create-self-service-experiences/setup-ui-for-action/setup-ui-for-action.md
=> Small formatting fix

docs/create-self-service-experiences/setup-ui-for-action/advanced-form-configurations.md
=> Add terraform examples of action

docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/templates/openshift.md
=> Removed title

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/checkmarx.md, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/resources/checkmarx/_example_checkmarx_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/resources/checkmarx/_example_checkmarx_webhook_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/resources/checkmarx/_example_python_script.mdx
Add checkmarx scan reports to Port
docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/checkmarx.md
docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/resources/checkmarx/
=> Add Checkmarx scan results to Port

docs/build-your-software-catalog/sync-data-to-catalog/ci-cd/github-workflow/github-workflow.md
=> Port-4367 Add Delete operation

docs/build-your-software-catalog/sync-data-to-catalog/git/gitops-using-port-crd.md, docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/port-crd.md
=> deploy small fixes to docs

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/pagerduty.md, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/sonarqube.md
=> Fixed grammer issue

docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/array.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/boolean.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/datetime.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/email.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/number.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/object.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/properties.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/string.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/team.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/timer.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/url.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/user.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/yaml.md
=> PORT-4118 Add enum colors and query string groups to all props

docusaurus.config.js
=> PORT-4415 Replace search provider in config

docs/sso-rbac/sso-providers/azure-ad.md
=> PORT-4465 Update group query section

docs/build-your-software-catalog/sync-data-to-catalog/webhook/webhook.md
=> Add terraform webhook example

docs/build-your-software-catalog/sync-data-to-catalog/aws/examples.md
Add AWS ECS Cluster example
- AWS Examples (`/build-your-software-catalog/sync-data-to-catalog/aws/examples.md`)
=> Add AWS ECS Cluster example

docs/create-self-service-experiences/setup-ui-for-action/user-inputs/entity.md
=> PORT-4577 Fix issue in action entity user input

docs/customize-pages-dashboards-and-plugins/dashboards/dashboards.md
=> PORT-4552-iframe-docs-fixes

docs/build-your-software-catalog/sync-data-to-catalog/api/api.md
=> PORT-4601 Update delete-all docs

docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/advanced.md, yarn.lock
=> Add docs for `search://` in GitLab 

docs/build-your-software-catalog/sync-data-to-catalog/git/_git_exporter_example_microservice_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/_git_exporter_example_repository_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/_bitbucket_exporter_example_monorepo_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/_bitbucket_exporter_example_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/examples.md, docs/build-your-software-catalog/sync-data-to-catalog/git/github/_github_exporter_example_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/example-issue/_git_exporter_example_issue_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/example-issue/_github_exporter_example_issue_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/example-monorepo/_github_exporter_example_monorepo_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/example-repository-folders/_github_exporter_example_folder_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/example-repository-folders/_github_exporter_example_pull_request_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/example-repository-folders/_github_exporter_example_repo_folders_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/example-workflow-workflowrun/_git_exporter_example_workflow_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/example-workflow-workflowrun/_github_exporter_example_wf_wfr_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples.md, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/_gitlab_exporter_example_merge_request_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/_gitlab_exporter_example_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/example-issue/_git_exporter_example_issue_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/example-issue/_gitlab_exporter_example_issue_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/example-pipeline-job/_git_exporter_example_pipeline_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/example-pipeline-job/_gitlab_exporter_example_pipeline_job_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/examples.md
=> PORT-4611 add folder mapping example to git hub docs

docs/build-your-software-catalog/sync-data-to-catalog/azure/installation.md
=> Add permissions requirements for deploying the azure integration

.github/CODEOWNERS
=> PORT-4649 Add Hadar to code owners on the docs

docs/resources.md
Add new Resources page for webinars and future content
Resources ('/resources')
=> add resources page for webinars and future content

docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/calculation-property/_category_.json, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/meta-properties.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/mirror-property/_category_.json, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/mirror-property/mirror-property.md, docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/proto.md, docs/build-your-software-catalog/sync-data-to-catalog/aws/examples.md, docs/build-your-software-catalog/sync-data-to-catalog/git/github/self-hosted-installation.md, docs/create-self-service-experiences/setup-backend/github-workflow/examples/scaffold-repositories-using-cookiecutter.md, docs/create-self-service-experiences/setup-backend/kafka/kafka.md
Changes:
* Added:
* Limitation section to the self hosted GitHub
* Documentation specifying to use fine-grained token with GitHub scaffolding action 
* Protobuf property
* Kafka consumer groups documentation
* Removed: 
* Example of resources in AWS cloud formation stack is 2 heavy, so we prefer to eliminate it by default
=> Fixed general problems in the docs

docusaurus.config.js, package-lock.json, package.json
Add hotjar to docs in order to view user sessions.
=> add hotjar to docs site

docs/build-your-software-catalog/sync-data-to-catalog/git/github/example-repository-dependabot-alerts/_github_exporter_example_dependabot_alert_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/example-repository-dependabot-alerts/_github_exporter_example_repo_dependabot_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples.md
=> [Github App] Minor adjustments to the dependabot alerts mapping and blueprint

docs/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty.md
=> remove client info

docs/guides-and-tutorials/scaffold-a-new-service.md
=> fix input name

docs/build-your-software-catalog/sync-data-to-catalog/git/github/_github_exporter_example_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/_github_exporter_example_pull_request_blueprint.mdx
Add pull request to repo relation in github example
- github_exporter_example_port_app_config (`/build-your-software-catalog/sync-data-to-catalog/git/github/_github_exporter_example_port_app_config.mdx`)
- github_exporter_example_pull_request_blueprint (`/build-your-software-catalog/sync-data-to-catalog/git/github/_github_exporter_example_pull_request_blueprint.mdx`)
=> Add pull request to repo relation in github example

docs/create-self-service-experiences/setup-ui-for-action/user-inputs/secret.md
=> Fix property decryption script

docs/create-self-service-experiences/set-self-service-actions-rbac/dynamic-permissions.md
=> add missing docs for dynamic permissions

docs/build-your-software-catalog/sync-data-to-catalog/incident-management/firehydrant.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/opsgenie.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty.md
=> reorder sidebar menu

docs/build-your-software-catalog/sync-data-to-catalog/sync-data-to-catalog.md
=> Update supported kinds of integrations

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/resources/swagger/_example_swagger_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/resources/swagger/_example_swagger_webhook_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/swagger.md
Added docs on ingesting swagger.json file into Port using API and webhook.
docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/resources/swagger/_example_swagger_blueprint.mdx
docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/resources/swagger/_example_swagger_webhook_config.mdx
docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/swagger.md
=> Add swagger api paths to port

docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/sentry.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/opsgenie.md
=> Add sentry docs of ocean

docs/build-your-software-catalog/sync-data-to-catalog/event-processing/kafka.md, docs/build-your-software-catalog/sync-data-to-catalog/git/github/github.md
Add currentIdentifier to github config mapping structure
- GitHub (`/build-your-software-catalog/sync-data-to-catalog/git/github/github.md`)
=> Add currentIdentifier to github config mapping structure

docs/quickstart.md
=> add quickstart video

docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube.md
Added a note to the Sonarqube integration about unsupported kind
docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube.md
=> Sonarqube Unsupported Kind Note

docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/kubecost.md
Added Kubecost ocean integration guide
docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/kubecost.md
=> Add Kubecost Docs

docs/build-your-software-catalog/sync-data-to-catalog/azure/examples.md, docs/build-your-software-catalog/sync-data-to-catalog/azure/examples/compute_resources/_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/azure/examples/compute_resources/_web_app_blueprint.mdx
=> Fix azure web app reference and add more references to azure docs

docs/guides-and-tutorials/scaffold-a-new-service.md
=> fix blueprint name

docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/mapping_extensions.md
=> added languages as a part of the mapping extensions

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/jenkins.md
=> fixed UI hyperlink

docs/guides-and-tutorials/scaffold-a-new-service.md
=> remove incorrect line

docs/create-self-service-experiences/setup-backend/github-workflow/examples/scaffold-repositories-using-cookiecutter.md, docs/guides-and-tutorials/scaffold-a-new-service.md
=> updated cookiecutter version

docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube.md
The Sonarqube ocean integration docs is very outdated. This PR updates it using the current configuration resources
docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube.md
=> update sonarqube config resources

docs/sso-rbac/rbac/rbac.md, docs/sso-rbac/sso-providers/azure-ad.md
=> PORT-5088 Update text about team management when SSO is enabled

docs/build-your-software-catalog/sync-data-to-catalog/incident-management/opsgenie.md
Added a sample payload data from the opsgenie integration
docs/build-your-software-catalog/sync-data-to-catalog/incident-management/opsgenie.md
=> Add opsgenie payload data

docs/build-your-software-catalog/sync-data-to-catalog/incident-management/firehydrant.md
Added payload data from FireHydrant
docs/build-your-software-catalog/sync-data-to-catalog/incident-management/firehydrant.md
=> Add firehydrant payload data

docs/guides-and-tutorials/scaffold-a-new-service.md
=> added informatino about SAML SSO orgs

docs/guides-and-tutorials/scaffold-a-new-service.md
=> noted a classic token is needed

docs/guides-and-tutorials/scaffold-a-new-service.md
=> aligned the SAML SSO bubble to appear

docs/create-self-service-experiences/setup-ui-for-action/user-inputs/secret.md
- Secret properties (missed a line in one of the examples)
=> PORT-5100-add-AES-GCM-docs-fix

docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/newrelic.md, docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk.md, docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty.md, docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira.md
=> [Integration][Sonarqube] Add once option example

docs/create-self-service-experiences/setup-backend/github-workflow/examples/deploy-cloudformation-template.md
Added AWS Cloudformation deployment examples using GitHub for:
- EC2 Instance
- S3 Bucket
- RDS Instance
- GitHub Action Example (`/create-self-service-experiences/setup-backend/github-workflow/examples/deploy-cloudformation-template.md`)
=> added cloudformation deployment using github

docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/sentry.md
Added Sentry projects and issues payload data from running the ocean integration
docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/sentry.md
=> Add Sentry payload data

docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/sentry.md
Added workflow to enable users to run the Sentry ocean integration once
=> Run Sentry Integration Once

docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/_gitlab_exporter_example_port_app_config.mdx
=> [Integration][Gitlab] Fix `merge-request` kind

docs/quickstart.md
=> PORT-5182 Make small fixes to the quickstart

docusaurus.config.js, package-lock.json, package.json, src/css/custom.css
=> change sidebar items font, implement image zoom on click

docs/guides-and-tutorials/visualize-service-k8s-runtime.md
=> revise config update

docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/_bitbucket_exporter_example_port_app_config.mdx
=> PORT-5211 Small typo fix in bitbucket examples

docs/integrations-index.md
=> reorder aws integs

docs/create-self-service-experiences/setup-ui-for-action/advanced-form-configurations.md
Added a terraform example for the visible action property attribute
=> PORT-5186-add-display-condition-property-in-terraform

docs/create-self-service-experiences/setup-ui-for-action/user-inputs/secret.md
=> PORT-5223-remove-fernet-from-docs

docs/create-self-service-experiences/setup-backend/github-workflow/examples/deploy-cloudformation-template.md
Updated RDS Cloudformation deployment to use aes256 secret because of fernet depreciation. 
- Cloudformation Example (`/create-self-service-experiences/setup-backend/github-workflow/examples/deploy-cloudformation-template.md`)
=> changed fernet secret decrypt to aes256

docs/integrations-index.md
=> PORT-5228 Fix formatting issue

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/azuredevops.md, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/azuredevops/_example_pipeline_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/azuredevops/_example_project_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/azuredevops/_example_repository_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/azuredevops/_example_webhook_configuration.mdx, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/azuredevops/_example_work_item_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/webhook/webhook.md
Added a python script  and webhook configuration files to ingest azure devops resources to Port
=> Add Azure Devops script and webhook

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/prometheus.md, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/prometheus/_example_alert_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/prometheus/_example_alert_webhook_config.mdx
configure Alertmanager to send webhook to Port
=> Prometheus Alertmanager

docs/integrations-index.md
=> port-5250 Add bitbucket app gitops

docs/create-self-service-experiences/setup-ui-for-action/advanced-form-configurations.md
=> move visible to be the first tab

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/argocd.md, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/argocd/_example_application_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/argocd/_example_project_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/resources/argocd/_example_webhook_configuration.mdx
=> Add argocd webhook configuration files

docs/create-self-service-experiences/setup-backend/circle-ci/circle-ci.md, docs/create-self-service-experiences/setup-backend/gitlab-pipeline/Installation.md, docs/create-self-service-experiences/setup-backend/port-execution-agent/Installation.md, docs/create-self-service-experiences/setup-backend/port-execution-agent/control-the-payload.md, docs/create-self-service-experiences/setup-backend/terraform-cloud/terraform-cloud.md
=> report back to port docs

docs/create-self-service-experiences/setup-backend/gitlab-pipeline/examples/deploy-s3-bucket-crossplane.md
=> fix blueprint typo

docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira.md
=> PORT-5272 Fix broken formatting

docs/create-self-service-experiences/setup-backend/gitlab-pipeline/Installation.md
=> extra information

docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/templates/full-kubernetes-exporter.md
=> Fixed docs link url

docs/integrations-index.md
=> PORT-5300 Make fixes and add new link

docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples.md
Fixed sentence to be more clear for when commiting the port-app-config.yaml
- ...
- ...
=> Fixed sentence to be more clear

docs/build-your-software-catalog/sync-data-to-catalog/git/_git_gitops_push_events_explanation.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/gitops/gitops.md, docs/build-your-software-catalog/sync-data-to-catalog/git/github/gitops/gitops.md, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/gitops/gitops.md
=> PORT-5306 Add note about gitops push events

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/datadog.md, docs/integrations-index.md
Ingest Datadog service catalog to Port using REST API
=> Ingest datadog service catalog

docs/build-your-software-catalog/sync-data-to-catalog/aws/Installation.md
=> fix admonitions

docs/build-your-software-catalog/sync-data-to-catalog/incident-management/firehydrant.md
Run FireHydrant Ocean integration once on Jenkins
=> Run Firehydrant once on Jenkins

docs/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty.md
=> Run Pagerduty once on Jenkins

docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/sentry.md
=> Run Sentry once on Jenkins

docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/newrelic.md
Run Newrelic once on Jenkins and Github
=> Run Newrelic once on jenkins and Github

docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/argocd.md
Run ArgoCD ocean integration on Jenkins pipeline
=> Run Argocd on Jenkins

docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/newrelic.md
Update the New Relic graphql url for users in EU
=> Newrelic URL for EU customers

docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/dynatrace.md, docs/integrations-index.md
Add Dynatrace entities ingestion script to docs
=> Ingest Dynatrace Entities

docs/build-your-software-catalog/sync-data-to-catalog/aws/examples.md, docs/create-self-service-experiences/setup-ui-for-action/advanced-form-configurations.md
…nfiguration
added option to use jqQuery for "required" attribute similarly to "default"
- Advanced form configuration (`docs/create-self-service-experiences/setup-ui-for-action/advanced-form-configurations.md`)
=> PORT-5312-Required-property-jq

docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/newrelic.md, docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/sentry.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/kubecost.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost.md, docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk.md, docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/firehydrant.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/opsgenie.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty.md, docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/argocd.md, docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira.md
=> handling container status code for ocean once

docs/sso-rbac/sso-providers/jumpcloud.md
=> added comment about on switch for email field

README.md
=> PORT-5506 Update README.md

docs/build-your-software-catalog/sync-data-to-catalog/git/_basic_file_properties_template.md, docs/build-your-software-catalog/sync-data-to-catalog/git/_relative_file_properties_template.md, docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/gitops/gitops.md
=> PORT-5537 Add missing sections to bitbucket GitOps

docs/build-your-software-catalog/sync-data-to-catalog/iac/terraform/modules/aws-exporter-module.md, docs/build-your-software-catalog/sync-data-to-catalog/webhook/webhook.md
=> fixes from docsly comments

docs/build-your-software-catalog/sync-data-to-catalog/aws/examples.md
Add AWS Elasticache cluster kind to AWS exporter
=> Add elasticache cluster to aws exporter

docs/quickstart.md
=> add querystring for git provider tabs

docs/quickstart.md
=> fix tab items

package-lock.json, src/components/tooltip/tooltip.jsx
=> fix tooltip zindex

docs/quickstart.md
=> small quickstart fixes

docs/guides-and-tutorials/scaffold-a-new-service.md
=> scaffold guide fixes

docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/example-pipeline-job/_git_exporter_example_pipeline_blueprint.mdx
=> Gitlab fix template for pipelines

docusaurus.config.js
=> PORT-5709 Activate last update time in docusaurus config

docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/Installation.md
=> added helm examples for port-agent

docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/advanced.md
=> add http proxy configuratino to port k8s exporter

docs/customize-pages-dashboards-and-plugins/page/catalog-page.md
=> add page deletion docs

docs/customize-pages-dashboards-and-plugins/page/catalog-page.md
=> page deletion fix

docs/build-your-software-catalog/sync-data-to-catalog/iac/terraform-cloud/_terraform_one_time_docker_parameters.mdx, docs/build-your-software-catalog/sync-data-to-catalog/iac/terraform-cloud/terraform-cloud.md, docs/build-your-software-catalog/sync-data-to-catalog/iac/terraform/examples/terraform.md
This PR holds an update to the terraform documentation, it adds documentation for terraform state version and outputs to the already existing docs.
- Terraform Cloud Docs (`/build-your-software-catalog/sync-data-to-catalog/iac/terraform-cloud`)
- ...
=> Terraform Cloud Integration Documentation Update

docs/integrations-index.md
=> PORT-5828 Some updates to integrations index

docs/create-self-service-experiences/security/security.md
=> PORT-5802 Add new IPs to security list

docs/guides-and-tutorials/visualize-service-k8s-runtime.md
=> PORT-5363 Update installation command

docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube.md, docs/build-your-software-catalog/sync-data-to-catalog/jira/jira.md
=> added jira and sonarqube ocean argocd docs

docs/search-and-query/search-and-query.md
=> add missing time filters to between operator

docs/build-your-software-catalog/sync-data-to-catalog/jira/jira.md
=> PORT-5427 Add example showing how to use JQL filtering with Ocean jira

docs/port-overview.md
=> fixed a url in overview page

docs/port-overview.md
=> Url fix overview 2

docs/faq/faq.md
=> fixed the security question of the FAQ

docs/build-your-software-catalog/sync-data-to-catalog/iac/terraform-cloud/terraform-cloud.md
=> docs: fix indentation and trailing /

docs/integrations-index.md
Added Integration index links to Trivy K8s and Azure Github workflow
docs/integrations-index.md
=> Add Azure Github workflow and Trivy to index page

docs/create-self-service-experiences/setup-ui-for-action/user-inputs/entity.md
=> port-6334 Update entity input docs

docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/installation.md
=> PORT-6336 Update glob patterns for project mapping to have 2 asterisks

docs/create-self-service-experiences/setup-ui-for-action/user-inputs/array.md, docs/create-self-service-experiences/setup-ui-for-action/user-inputs/boolean.md, docs/create-self-service-experiences/setup-ui-for-action/user-inputs/datetime.md, docs/create-self-service-experiences/setup-ui-for-action/user-inputs/entity.md, docs/create-self-service-experiences/setup-ui-for-action/user-inputs/number.md, docs/create-self-service-experiences/setup-ui-for-action/user-inputs/object.md, docs/create-self-service-experiences/setup-ui-for-action/user-inputs/text.md, docs/create-self-service-experiences/setup-ui-for-action/user-inputs/user.md, docs/promote-scorecards/usage.md
=> [Terraform] Remove `required=false` from action properties & update scorecard schema

docs/build-your-software-catalog/sync-data-to-catalog/git/github/example-repository-admins/_github_export_example_repository_with_admins_relation_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/example-repository-admins/_github_exporter_example_admins_users_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/example-repository-admins/_github_exporter_example_github_users_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/example-repository-admins/_github_exporter_example_users_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples.md
=> PORT-6738 Add docs for users and admins

docs/build-your-software-catalog/sync-data-to-catalog/ci-cd/jenkins.md
Update the Jenkins Integration to include the `users` kind
- Jenkins Integration (`/build-your-software-catalog/sync-data-to-catalog/ci-cd/jenkins.md`)
=> PORT-6392 Add the user kind to the Jenkins Integration

docs/create-self-service-experiences/setup-backend/github-workflow/examples/deploy-cloudformation-template.md
=> improve cloudformation example page

docs/build-your-software-catalog/define-your-data-model/setup-blueprint/properties/calculation-property/calculation-property.md
=> remove incorrect pitfalls paragraph

docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/aws-cost.md, docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/templates/trivy.md, docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/trivy.md
Connect Trivy Python script with Trivy k8s exporter
docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/templates/trivy.md
docs/build-your-software-catalog/sync-data-to-catalog/webhook/examples/packages/trivy.md
=> Connect Trivy Python script with Trivy k8s exporter

docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/kubernetes.md
=> fixed argo application yaml and added helm version docs

docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/templates/fluxcd.md
Added documentation for FluxCD K8s exporter
docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/templates/fluxcd.md
docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/templates/kyverno.md
=> Add FluxCD documentation

docs/search-and-query/search-and-query.md
=> added notbetween to docs

docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/control-the-payload.md, docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/installation-methods/argocd.md, docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/installation-methods/docker.md, docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/installation-methods/helm.md
=> agent docker installation example

docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/advanced.md
=> Gitlab additional parameters

docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/examples/compute_resources/_aks_blueprint.mdx
=> fix typo in AKS instead of ASK

docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/Installation.md
=> PORT-4943 Fix broken links in AWS exporter installation docs

docs/build-your-software-catalog/customize-integrations/configure-mapping.md
=> remove title

docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/Installation.md, docs/guides-and-tutorials/scaffold-a-new-service.md
Typos and corrections to links in docs.
- docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/Installation.md
- docs/guides-and-tutorials/scaffold-a-new-service.md
=> adding fixes from PORT-6834

docs/build-your-software-catalog/sync-data-to-catalog/git/github/example-repository-alerts/_github_exporter_example_repo_dependabot_port_app_config.mdx
=> updated dependabot alert URL in mapping example

docs/create-self-service-experiences/set-self-service-actions-rbac/dynamic-permissions.md
Added another use case to dynamic permissions page to help users understand the possibilities available with dynamic permissions.
- docs/create-self-service-experiences/set-self-service-actions-rbac/dynamic-permissions.md
=> adding single additional use case for dynamic permissions

docs/create-self-service-experiences/setup-ui-for-action/user-inputs/array.md, docs/create-self-service-experiences/setup-ui-for-action/user-inputs/datetime.md, docs/create-self-service-experiences/setup-ui-for-action/user-inputs/email.md, docs/create-self-service-experiences/setup-ui-for-action/user-inputs/entity.md, docs/create-self-service-experiences/setup-ui-for-action/user-inputs/number.md, docs/create-self-service-experiences/setup-ui-for-action/user-inputs/object.md, docs/create-self-service-experiences/setup-ui-for-action/user-inputs/secret.md, docs/create-self-service-experiences/setup-ui-for-action/user-inputs/team.md, docs/create-self-service-experiences/setup-ui-for-action/user-inputs/text.md, docs/create-self-service-experiences/setup-ui-for-action/user-inputs/toggle.md, docs/create-self-service-experiences/setup-ui-for-action/user-inputs/url.md, docs/create-self-service-experiences/setup-ui-for-action/user-inputs/user-inputs.md, docs/create-self-service-experiences/setup-ui-for-action/user-inputs/user.md, docs/create-self-service-experiences/setup-ui-for-action/user-inputs/yaml.md
=> revise boolean action input docs

src/css/custom.css
=> update font to match rebranding

docs/build-your-software-catalog/sync-data-to-catalog/iac/terraform/terraform.md
=> moved bubble outside tab

docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace.md, docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/newrelic.md, docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/sentry.md, docs/build-your-software-catalog/sync-data-to-catalog/ci-cd/jenkins.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/kubecost.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost.md, docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk.md, docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube.md, docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md, docs/build-your-software-catalog/sync-data-to-catalog/event-processing/kafka.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/firehydrant.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/opsgenie.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty.md, docs/build-your-software-catalog/sync-data-to-catalog/itsm/servicenow.md
=> changed integration github workflow to use ocean sail instead of docker

docs/build-your-software-catalog/customize-integrations/configure-mapping.md
=> add example for splitting a kind for relation

docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk/snyk.md
=> added note for the skipp in case of SNYK-9999

docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/resource-mapping-examples.md
=> hotfix: additional deletion was missing

docs/build-your-software-catalog/sync-data-to-catalog/argocd/argocd.md, docs/build-your-software-catalog/sync-data-to-catalog/feature-management/launchdarkly.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/servicenow.md, docs/build-your-software-catalog/sync-data-to-catalog/terraform-cloud/terraform-cloud.md
=> switch Argo to use oecan sail on GH

.github/dependabot.yml, .github/dependebot.yml
=> Update and rename dependebot.yml to dependabot.yml

docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/examples.md, docs/build-your-software-catalog/sync-data-to-catalog/git/github/github.md, docs/create-self-service-experiences/setup-backend/github-workflow/examples/delete-repository.md, docs/customize-pages-dashboards-and-plugins/page/dashboard-page.md
=> PORT-7647 Remove unnecessary page and fix broken links

docs/build-your-software-catalog/custom-integration/api/ci-cd/github-workflow/guides/dora-metrics.md
The change presents a improvement to the existing implementation by making the scripts for computing dora metrics independent of github.
- Resource Path - (/build-your-software-catalog/custom-integration/api/ci-cd/github-workflow/guides/dora-metrics)
=> PORT-7715 | Make Dora Metrics Script Platform Agnostic

docs/create-self-service-experiences/set-self-service-actions-rbac/set-self-service-actions-rbac.md
=> Triggering an Action on Behalf of Another User

docs/customize-pages-dashboards-and-plugins/dashboards/dashboards.md
Added docs for the new "number chart" form configurations.
=> update number chart docs

docs/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty.md
Updated the oncall user to map the user with the highest escalation level
docs/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty.md
=> Update PagerDuty oncall mapping

docs/create-self-service-experiences/setup-backend/gitlab-pipeline/examples/deploy-s3-bucket-crossplane.md
=> removed the [] symbol in the action

docs/search-and-query/search-and-query.md
=> added a few explanations in the search and query page

docs/create-self-service-experiences/setup-backend/github-workflow/examples/create-github-secret.md, docs/create-self-service-experiences/setup-backend/github-workflow/examples/delete-repository.md, docs/create-self-service-experiences/setup-backend/github-workflow/examples/manage-pull-requests.md
This reverts commit 1b6ce1a1205aae88c6475f3b9511b4d6f9b6c6df.
Performing a revert because these docs were updated before the actual feature was deployed
- ...
- ...
=> Revert PORT-7795 Change github actions (#1129)

docs/create-self-service-experiences/setup-backend/github-workflow/examples/Azure/create-azure-resource.md, docs/create-self-service-experiences/setup-backend/github-workflow/examples/Azure/tag-azure-resource.md
This reverts commit f9b3992df51637ef1d8bbedf99ae85266be28595.
This is a revert of #1130 which was accidentally merged to main before the frontend feature was released
=> PORT-7658-revert-accidental-merge-to-main

docs/create-self-service-experiences/setup-backend/azure-pipeline/examples/examples.md, docs/create-self-service-experiences/setup-backend/gitlab-pipeline/examples/examples.md, docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/examples.md, docs/search-and-query/search-and-query.md
=> Small fixes

docs/build-your-software-catalog/sync-data-to-catalog/feature-management/_launchdarkly_one_time_docker_parameters.mdx, docs/build-your-software-catalog/sync-data-to-catalog/feature-management/launchdarkly.md, docs/create-self-service-experiences/setup-backend/github-workflow/examples/Launchdarkly/toggle-launchdarkly-feature-flag.md
=> PORT-7922 Fix some typos and formatting in LD integration docs and guides

docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/example-repository-alerts/_github_exporter_example_codeScan_alert_blueprint.mdx
=> change title to be uppercase

docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/add-tags-to-ecr-repository.md, docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/add-tags-to-s3-bucket.md, docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/create-an-ec2-instance.md, docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/create-eks-cluster-and-deploy-app.md, docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/deploy-cloudformation-template.md, docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/manage-ec2-instances.md, docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/push-image-to-ecr.md, docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/terraform-plan-and-apply-aws-resource.md
- docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/add-tags-to-ecr-repository.md
- docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/add-tags-to-s3-bucket.md
- docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/create-eks-cluster-and-deploy-app.md
- docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/deploy-cloudformation-template.md
- docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/manage-ec2-instances.md
- docs/create-self-service-experiences/setup-backend/github-workflow/exa …
=> Port 7794 update GitHub actions for aws

docs/create-self-service-experiences/setup-backend/github-workflow/examples/Launchdarkly/toggle-launchdarkly-feature-flag.md, package-lock.json, package.json
Update Self Service Guides for `Toggle Launchdarkly Feature Flag` action following the new self service actions api
- Resource Path (`/create-self-service-experiences/setup-backend/github-workflow/examples/Launchdarkly/toggle-launchdarkly-feature-flag`)
=> PORT-7789 | Updated Toggle Launchdarkly Feature Flag Action docs following new actions api

docs/create-self-service-experiences/setup-backend/github-workflow/examples/Opsgenie/create-an-incident.md
=> PORT-7658-update-pager-duty-incident-docs

docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/create-an-ec2-instance.md, package-lock.json, package.json
Update Self Service Guides for `Create EC2 Instance` action following the new self service actions api
- Resource Path (`/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/create-an-ec2-instance`)
=> PORT-7796 | Updated Create EC2 Action docs following new actions api

docs/create-self-service-experiences/setup-backend/azure-pipeline/azure-pipeline.md, docs/create-self-service-experiences/setup-backend/azure-pipeline/examples/create-azure-resource.md, docs/create-self-service-experiences/setup-backend/azure-pipeline/examples/scaffold-repositories-using-cookiecutter.md, docs/create-self-service-experiences/setup-backend/circle-ci/circle-ci.md, docs/create-self-service-experiences/setup-backend/cloudbuild-pipeline/cloudbuild-pipeline.md, docs/create-self-service-experiences/setup-backend/gitlab-pipeline/examples/add-ec2-volume.md, docs/create-self-service-experiences/setup-backend/gitlab-pipeline/examples/create-ec2-instance.md, docs/create-self-service-experiences/setup-backend/gitlab-pipeline/examples/create-k8s-namespace.md, docs/create-self-service-experiences/setup-backend/gitlab-pipeline/examples/report-a-bug.md, docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/deploy-azure-resource.md, docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/scaffold-bitbucket-using-cookiecutter.md, docs/create-self-service-experiences/setup-backend/jenkins-pipeline/examples/scaffold-github-using-cookiecutter.md, docs/create-self-service-experiences/setup-backend/jenkins-pipeline/jenkins-pipeline.md, docs/create-self-service-experiences/setup-backend/terraform-cloud/terraform-cloud.md, docs/create-self-service-experiences/setup-backend/webhook/examples/software-templates.md, docs/create-self-service-experiences/setup-backend/webhook/examples/terraform-no-code-resource-provisioning.md, docs/create-self-service-experiences/setup-backend/webhook/kafka/examples/execution-basic-runner-using-aws-lambda.md, docs/create-self-service-experiences/setup-backend/webhook/local-debugging-webhook.md, docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/examples/Argo Workflows/trigger-an-argo-workflow.md
=> PORT-7957 | Update the Docs for the new action api

docs/create-self-service-experiences/setup-backend/webhook/port-execution-agent/control-the-payload.md
=> add note for available methods of defining payload

docs/promote-scorecards/usage.md
Add a reference to the different rules operators for scorecards.
- Promote Scorecard Usage (`/promote-scorecards/usage.md`)
=> Add link to scorecards operators

docs/create-self-service-experiences/setup-backend/github-workflow/examples/AWS/push-image-to-ecr.md
=> PORT-8059 Rename guide and add tags

docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/bitbucket.md, docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/gitops/gitops.md
=> improve bitbucket docs

docs/guides-and-tutorials/ensure-production-readiness.md, docs/quickstart.md, docs/resources.md
=> add production readiness video to docs

docs/create-self-service-experiences/setup-backend/setup-backend.md
=> add note about jq key to payload docs

docs/guides-and-tutorials/let-developers-enrich-services-using-gitops.md
=> improve payload for gitops guide

docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/kubernetes.md, docs/guides-and-tutorials/manage-resources-using-k8s-crds.md, docs/guides-and-tutorials/visualize-service-k8s-runtime.md
=> fix eventListenerType to eventListener.type

docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk/snyk.md
=> PORT-8376 Add Snyk target JSON

docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/_sentry-docker-parameters.mdx, docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/sentry.md
=> PORT-8390 Update guidance on Sentry integration parameters

docs/promote-scorecards/promote-scorecards.md
=> adjust hint for scorecard levels

docs/build-your-software-catalog/customize-integrations/configure-mapping.md
=> add note about disabling raw data examples

docs/build-your-software-catalog/custom-integration/webhook/webhook.md
=> update delete operation in webhook integrations

docs/search-and-query/global-search.md
=> remove misleading link

docs/build-your-software-catalog/sync-data-to-catalog/terraform-cloud/terraform-cloud.md
=> added mention for Terraform Enterprise

docs/api-reference/get-organization-details.api.mdx, docs/api-reference/patch-organization-details.api.mdx, docs/api-reference/sidebar.ts, docs/api-reference/update-organization-details.api.mdx, static/spectmp.yaml
=> add org api docs

docs/guides-and-tutorials/create-slack-channel-for-reported-incident.md
=> fixed typo

docs/customize-pages-dashboards-and-plugins/dashboards/dashboards.md
=> add line chart use case

docs/build-your-software-catalog/customize-integrations/configure-mapping.md
=> add search query relation docs

docs/build-your-software-catalog/sync-data-to-catalog/git/github/_github_exporter_supported_resources.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/example-repository-release-tag/_github_exporter_example_release_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/example-repository-release-tag/_github_exporter_example_release_tag_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/example-repository-release-tag/_github_exporter_example_tag_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/resource-mapping-examples.md, docs/build-your-software-catalog/sync-data-to-catalog/git/github/github.md
=> PORT-8780 docs for tags & releases 

docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/bitbucket.md, docs/build-your-software-catalog/sync-data-to-catalog/git/github/github.md
=> revise mapping docs to match new ui

docs/troubleshooting.md
=> add session timeout mechanism

docs/actions-and-automations/templates/_backend-types-json.md
=> add missing backend info

docs/customize-pages-dashboards-and-plugins/dashboards/dashboards.md
=> add line chart properties

docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installations/multi_account.md
hotfix
- multi accounts (`/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installations/multi_account`)
=> removed useless comment

docs/sso-rbac/sso-providers/saml/google-workspace.md, docs/sso-rbac/sso-providers/saml/jumpcloud.md
=> PORT-9002 Replace relative paths with absolute in SAML docs

docs/build-your-software-catalog/set-catalog-rbac/set-catalog-rbac.md
=> add docs for blueprint read permissions

docs/actions-and-automations/create-self-service-experiences/create-self-service-experiences.md, docs/actions-and-automations/create-self-service-experiences/setup-the-backend/setup-the-backend.md, docs/actions-and-automations/create-self-service-experiences/setup-ui-for-action/setup-ui-for-action.md, docs/actions-and-automations/setup-backend/github-workflow/examples/AWS/create-eks-cluster-and-deploy-app.md, docs/actions-and-automations/setup-backend/github-workflow/examples/kubernetes/manage-clusters.md, docs/build-your-software-catalog/build-your-software-catalog.md, docs/build-your-software-catalog/custom-integration/api/api.md, docs/build-your-software-catalog/customize-integrations/configure-data-model/relate-blueprints/relate-blueprints.md, docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/setup-blueprint.md, docs/build-your-software-catalog/customize-integrations/configure-mapping.md, docs/build-your-software-catalog/set-catalog-rbac/set-catalog-rbac.md, docs/guides-and-tutorials/ensure-production-readiness.md, docs/guides-and-tutorials/manage-resources-using-k8s-crds.md, docs/port-overview.md, docs/resources.md, src/css/custom.css
=> resize youtube embeds, make menu caret smaller

docs/build-your-software-catalog/sync-data-to-catalog/git/github/_github_exporter_supported_resources.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/advanced.md, docs/build-your-software-catalog/sync-data-to-catalog/git/github/github.md
=> github file kind support

docs/build-your-software-catalog/sync-data-to-catalog/git/github/github.md
=> revise example

docs/actions-and-automations/define-automations/examples.md
=> add before expression

docs/build-your-software-catalog/custom-integration/iac/pulumi/pulumi.md
=> remove outdated admonition

docs/guides-and-tutorials/scaffold-a-new-service.md
Fix grammar mistake in scaffold-a-new-service page
=> Documentation grammar fix

docs/integrations-index.md
Add Statuspage to integrations index
- Intergations Index (`/docs/integrations-index.md`)
=> Add Statuspage to integrations index

docs/actions-and-automations/setup-backend/azure-pipeline/azure-pipeline.md, docs/api-reference/create-an-action-automation.api.mdx, docs/api-reference/delete-an-action-automation.api.mdx, docs/api-reference/get-actions-automations.api.mdx, docs/api-reference/get-an-action-automation.api.mdx, docs/api-reference/sidebar.ts, docs/api-reference/update-an-action-automation.api.mdx, docs/api-reference/update-an-actions-permissions.api.mdx, docs/build-your-software-catalog/customize-integrations/configure-data-model/relate-blueprints/relate-blueprints.md, docusaurus.config.js, src/css/custom.css, static/spectmp.yaml
=> add missing api docs

docs/integrations-index.md, docs/sso-rbac/rbac/rbac.md, docs/sso-rbac/sso-providers/azure-ad.md, docs/sso-rbac/sso-providers/oidc/_category_.json, docs/sso-rbac/sso-providers/oidc/oidc.md, docs/sso-rbac/sso-providers/oidc/okta.md, docs/sso-rbac/sso-providers/oidc/onelogin.md, docs/sso-rbac/sso-providers/saml/_category_.json
=> added a generic oidc sso page

docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples/cloud_resource/_port_app_config.mdx
- **feat: add useGetResource to examples**
- **feat: rename useGetResource to useGetResourceAPI**
- ...
- ...
=> feat Ocean AWS add useGetResource to examples

docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/example-file-kind/_example_package_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/example-file-kind/_package_json_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/resource-mapping-examples.md
=> add file mapping example

docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/datadog.md, docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace.md, docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/newrelic.md, docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/sentry.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/kubecost.md, docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk/snyk.md, docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/sonarqube.md, docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md, docs/build-your-software-catalog/sync-data-to-catalog/feature-management/launchdarkly/launchdarkly.md, docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/installation.md, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/installation.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/firehydrant.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/opsgenie.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/servicenow.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage.md, docs/build-your-software-catalog/sync-data-to-catalog/jenkins/jenkins.md, docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira/jira.md, docs/build-your-software-catalog/sync-data-to-catalog/project-management/linear/linear.md, docs/build-your-software-catalog/sync-data-to-catalog/templates/_ocean_saas_installation.mdx, docs/build-your-software-catalog/sync-data-to-catalog/terraform-cloud/terraform-cloud.md
=> move ocean saas to main installation option

docs/actions-and-automations/create-self-service-experiences/set-self-service-actions-rbac/dynamic-permissions.md, docs/guides-and-tutorials/let-developers-enrich-services-using-gitops.md
=> clarify dynamic permissions

docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installations/multi_account.md
=> Fixed integration account permissions code snippet

docs/build-your-software-catalog/sync-data-to-catalog/git/github/github.md, docs/build-your-software-catalog/sync-data-to-catalog/templates/_ocean_saas_installation.mdx, docs/generalTemplates/_beta_feature_notice.md, docs/sso-rbac/rbac/rbac.md
=> clarify beta notifications

docs/sso-rbac/sso-providers/azure-ad.md
Some users who set up SSO ask for connection name prior to providing App ID and Client Secret value. I would like to link the information Port requires at the top of the AzureAD page (where users tend to struggle) so that they know Port needs two pieces of information from them to get started,
- docs/sso-rbac/sso-providers/azure-ad.md
=> link to azureAd things needed

docs/build-your-software-catalog/sync-data-to-catalog/git/github/github.md
=> add docs for multi doc yamls

docs/build-your-software-catalog/sync-data-to-catalog/templates/_ocean_saas_installation.mdx
=> add beta notice for ocean saas

docs/actions-and-automations/setup-backend/send-slack-message/send-slack-message.md, docs/api-reference/create-credentials.api.mdx, docs/api-reference/delete-credentials.api.mdx, docs/api-reference/get-all-credentials.api.mdx, docs/api-reference/rotate-secret.api.mdx, docs/api-reference/sidebar.ts, docs/api-reference/update-credentials.api.mdx, docs/customize-pages-dashboards-and-plugins/dashboards/dashboards.md, static/apispec.yaml
=> add apps api routes

docs/security.md
=> PORT-9648 security page updates

docs/sso-rbac/sso-providers/saml/azure-ad.md
=> fixed Azure AD SAML requirements for SSO:

docs/guides-and-tutorials/create-cloud-resource-using-iac.md, docs/guides-and-tutorials/create-slack-channel-for-reported-incident.md
Changed several typos and references that didn't work properly
- `/guides-and-tutorials/create-slack-channel-for-reported-incident/`
- `/guides-and-tutorials/create-cloud-resource-using-iac/`
=> PORT-9644 - Fixes to guides

docs/build-your-software-catalog/sync-data-to-catalog/templates/_ocean_saas_installation.mdx
=> update ocean saas adminition

docs/actions-and-automations/define-automations/examples.md
Added a new example to the automation section on entity update type.
- Automation (`https://docs.getport.io/actions-and-automations/define-automations/examples`)
=> Added new automation example for entity update

docs/build-your-software-catalog/sync-data-to-catalog/templates/_ocean_saas_installation.mdx
=> add ocean saas allowlist ips

docs/actions-and-automations/create-self-service-experiences/create-self-service-experiences.md
=> update self service action video

docs/build-your-software-catalog/sync-data-to-catalog/git/github/_github_exporter_supported_resources.mdx
=> update available github resources

docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/_gitlab_exporter_supported_resources.mdx
=> Add file kind to support resources in the docs

docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/installation.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/_create-service-account-and-key.mdx, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/installation.md
=> [GCP] Add docs for github action run

docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/installation.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/installation.md
=> [GCP][Azure] Fix github workflow example

docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/newrelic.md
Added docs on how to ingest New Relic service level objectives and indicators
- ...
- ...
=> [New Relic] - Add Service Level docs

docs/sso-rbac/rbac/rbac.md
=> add users and teams as bp changes to search queries

docs/sso-rbac/sso-providers/saml/azure-ad.md, docs/sso-rbac/sso-providers/saml/jumpcloud.md, docs/sso-rbac/sso-providers/saml/okta.md, docs/sso-rbac/sso-providers/saml/saml.md
=> PORT-10004 Comment out SCIM docs for the time being

docs/actions-and-automations/define-automations/setup-action.md, docs/actions-and-automations/define-automations/setup-trigger.md
=> comment unavailable trigger types

docs/guides/all/visualize-service-k8s-runtime.md
Changed `+ Add` to `+ Widget` due to change in homepage.
- Visualize service k8s runtime (`/guides/all/visualize-service-k8s-runtime`)
=> Change add button text to widget text

docs/promote-scorecards/promote-scorecards.md
- Scorecards (`/promote-scorecards`)
=> fix: containsAny accepted value

docs/actions-and-automations/define-automations/setup-action.md, docs/actions-and-automations/define-automations/setup-trigger.md
=> add docs for new automation trigger types

docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/example-file-kind/_package_json_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/github.md, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/example-file/_gitlab_exporter_example_package_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/gitlab.md
=> fix gitlab file kind comment

docs/actions-and-automations/create-self-service-experiences/create-self-service-experiences.md, docs/actions-and-automations/create-self-service-experiences/setup-the-backend/setup-the-backend.md, docs/actions-and-automations/create-self-service-experiences/templates/_execute_action_locations.mdx
=> add action execution methods

src/components/guides-section/GuidePage/GuidePage.jsx
=> remove url params on clear filters button click

docs/build-your-software-catalog/sync-data-to-catalog/incident-management/opsgenie.md
=> Migration guide for opsgenie version 0.2.0

docs/actions-and-automations/setup-backend/webhook/webhook.md
=> port-10449 Missing .event in properties usage

docs/promote-scorecards/examples.md
Added example scorecard that count number of entities related.
- scorecards (
=> Add example of no. of entities for scorecards

docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/installation.md
Added a new variable to the gcp terraform module- The custom roles variable
- GCP teraform installation method (`/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/installation?installation-platforms=terraform`)
=> [GoogleCloud] Added new variable to the gcp terraform module

docs/promote-scorecards/examples.md
Fixes based on PR #1593 
- Scorecards examples
=> Scorecards text fixes

docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/example-teams/_azuredevops_exporter_example_team_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/example-branch/_git_exporter_example_branch_blueprint.mdx
Some small fixes (many should be false for branch to repo blueprint, trailing comma in ADO teams blueprint).
- docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/example-teams/_azuredevops_exporter_example_team_blueprint.mdx
- docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/example-branch/_git_exporter_example_branch_blueprint.mdx
=> Small modifications to git docs

docs/actions-and-automations/define-automations/setup-action.md
=> remove the affected entities from the doc

docs/sso-rbac/rbac/rbac.md
=> add api region note

docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/example-branch/_git_exporter_example_branch_protection_blueprint.mdx
=> fix relation limit

docs/api-reference/get-all-users-in-your-organization.api.mdx, docs/promote-scorecards/promote-scorecards.md, static/apispec.yaml
=> Spec link update

docs/sso-rbac/rbac/rbac.md
Move the UTB requirement to the info callout
=> Update service account info

docs/guides/all/iam-permissions-guide.md
♫ Fixing typos
N/A
docs/guides/all/iam-permissions-guide.md
=> Fix typos in iam-permissions-guide.md

docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/datadog/datadog.md, docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace/dynatrace.md, docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/newrelic.md, docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/sentry.md, docs/build-your-software-catalog/sync-data-to-catalog/argocd/argocd.md, docs/build-your-software-catalog/sync-data-to-catalog/cicd/jenkins/jenkins.md, docs/build-your-software-catalog/sync-data-to-catalog/cicd/octopus-deploy/octopus-deploy.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/kubecost/kubecost.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-cost/opencost.md, docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk/snyk.md, docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/sonarqube.md, docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/wiz.md, docs/build-your-software-catalog/sync-data-to-catalog/event-processing/kafka.md, docs/build-your-software-catalog/sync-data-to-catalog/feature-management/launchdarkly/launchdarkly.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/firehydrant.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/opsgenie.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty/pagerduty.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/servicenow.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/statuspage.md, docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira/jira.md, docs/build-your-software-catalog/sync-data-to-catalog/project-management/linear/linear.md, docs/build-your-software-catalog/sync-data-to-catalog/terraform-cloud/terraform-cloud.md
=> update ocean sail workflows

docs/api-reference/change-an-entity.api.mdx, docs/api-reference/create-an-entity.api.mdx, static/apispec.yaml
=> update entity routes

docs/api-reference/pages.mdx, docs/api-reference/sidebar.ts
=> add pages notification to API docs

docs/api-reference/get-all-users-in-your-organization.api.mdx, src/components/guides-section/consts.js, static/apispec.yaml
=> small api fix

docs/actions-and-automations/setup-backend/webhook/port-execution-agent/installation-methods/docker.md
- Docker (`/actions-and-automations/setup-backend/webhook/port-execution-agent/installation-methods/docker `)
=> fix: update port-agent installation using docker

package-lock.json, package.json
=> upgrade docusaurus version to 3.6.0

docs/guides/all/ingest-vulnerability-alerts-from-orca-security-using-a-custom-webhook-integration.md
=> fix guide sidebar

docs/customize-pages-dashboards-and-plugins/dashboards/dashboards.md
=> add docs to markdown widget

package-lock.json, package.json
=> upgrade docusaurus version to 3.6.1

docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installations/multi_account.md
=> fix trust relationship

docs/build-your-software-catalog/sync-data-to-catalog/sync-data-to-catalog.md, docs/customize-pages-dashboards-and-plugins/page/catalog-page.md, docs/guides/all/connect-github-pr-with-sonar-analysis.md, docs/guides/all/connect-github-repository-with-sonarqube-project.md, docs/guides/all/connect-jira-issue-to-service.md, docs/guides/all/create-cloud-resource-using-iac.md, docs/guides/all/deploy-s3-bucket-crossplane.md, docs/guides/all/ingest-cloud-resources-using-newrelic.md, docs/guides/all/ingest-dependencies-from-package-json-to-service.md, docs/guides/all/s3-using-webhook.md, docs/guides/all/tag-azure-resource.md, docs/guides/all/toggle-launchdarkly-feature-flag.md, docs/integrations-index.md, docs/sso-rbac/rbac/rbac.md, docs/troubleshooting.md
=> fix broken links

docs/api-reference/cancel-a-migration.api.mdx, docs/api-reference/get-a-migration.api.mdx, docs/api-reference/sidebar.ts, static/apispec.yaml
=> add migration routes

docs/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty/example.md
=> fix default mapping for incident url

docs/api-reference/pages.mdx
=> PORT-11462 Add danger admonition to the pages API page

docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installations/multi_account.md
Description
Updated docs pages
AWS Multi-account (build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/installations/multi_account)
=> feat: combine integration permissions

package-lock.json, package.json
=> upgrade docusaurus version to 3.6.2

docs/sso-rbac/sso-providers/_scim_functionality_list.mdx, docs/sso-rbac/sso-providers/oidc/okta.md
=> removed groups from okta

package-lock.json, package.json
=> update styled package

docs/build-your-software-catalog/sync-data-to-catalog/sync-data-to-catalog.md, src/components/guides-section/consts.js
=> add servicenow guide label, remove integration diagram

package-lock.json, package.json
=> upgrade docusaurus version to 3.6.3

docs/build-your-software-catalog/custom-integration/webhook/webhook.md
=> PORT-11688 Add note about custom webhooks response status code

docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/example-repository-alerts/_github_exporter_example_dependabot_alert_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/example-repository-alerts/_github_exporter_example_repo_dependabot_port_app_config.mdx
=> PORT-7766 Update dependabot mapping example in the docs

docs/build-your-software-catalog/sync-data-to-catalog/event-processing/kafka.md
Restructured kafka integration guide to conform to new structure
Kafka (`/build-your-software-catalog/sync-data-to-catalog/event-processing/kafka`)
=> PORT-11598 Kafka Integration guide refactoring

docs/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty/examples.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty/pagerduty.md
Added support for pagerduty users and incident improvements
docs/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty/examples.md
docs/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty/pagerduty.md
=> [Integration] [PagerDuty] - Add Pagerduty Users and Incident Improvement

docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira/examples/_jira_example_issue_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira/examples/_jira_example_issue_configuration.mdx, docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira/examples/_jira_exporter_example_user_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira/examples/_jira_exporter_example_user_configuration.mdx, docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira/examples/_jira_issue_example_entity.mdx, docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira/examples/_jira_user_example_entity.mdx, docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira/examples/_jira_user_example_response.mdx, docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira/jira.md
- Adds Jira User Blueprint with related configuration and examples
- Updates Jira Issue Blueprint to include user relations and new examples
- Adds handling duration calculation property to Issue Blueprint
- Updates documentation with new example files and response data
This PR enhances the Jira integration documentation by adding complete User blueprint support and updating the Issue blueprint to better handle user relationships.
It also adds examples and sample responses to make the integration process clearer.
- Jira User Blueprint Example (`/build-your-software-catalog/project-management/jira/examples/_jira_exporter_example_user_blueprint.mdx`)
- Jira User Configuration Example (`/build-your-software-catalog/project-management/jira/examples/_jira_exporter_example_user_configuration.mdx …
=> feat: Add Users Examples to Jira Docs

docusaurus.config.js
=> make modal text bigger

docs/api-reference/change-a-team.api.mdx, docs/api-reference/create-a-team.api.mdx, docs/api-reference/create-credentials.api.mdx, docs/api-reference/delete-a-team.api.mdx, docs/api-reference/delete-a-user.api.mdx, docs/api-reference/delete-credentials.api.mdx, docs/api-reference/get-a-team.api.mdx, docs/api-reference/get-a-user.api.mdx, docs/api-reference/get-all-credentials.api.mdx, docs/api-reference/get-all-teams-in-your-organization.api.mdx, docs/api-reference/get-all-users-in-your-organization.api.mdx, docs/api-reference/invite-a-user-to-your-organization.api.mdx, docs/api-reference/patch-a-team.api.mdx, docs/api-reference/patch-a-user.api.mdx, docs/api-reference/rotate-secret.api.mdx, docs/api-reference/update-credentials.api.mdx, static/apispec.yaml, static/rawApiSpec.yaml
=> update api spec

docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/sentry.md, docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/templates/_template_installation.mdx, docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/templates/_template_prerequisites.mdx, docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/templates/fluxcd.md, docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/templates/full-kubernetes-exporter.md, docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/templates/istio.md, docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/templates/knative.md, docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/templates/kyverno.md, docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/templates/openshift.md, docs/build-your-software-catalog/sync-data-to-catalog/kubernetes/templates/trivy.md
=> add selector to mapping snippets, prettify pages

docs/api-reference/execute-a-self-service-action.api.mdx, docs/api-reference/get-an-action-runs-details.api.mdx, docs/api-reference/patch-an-action-run.api.mdx, static/apispec.yaml, static/rawApiSpec.yaml
=> update api lib and fix responses

docs/build-your-software-catalog/custom-integration/iac/terraform/terraform.md
Fix code block indentation in "Build a software catalog -> Create a custom integration -> IaC -> Terraform"
None 
`build-your-software-catalog/custom-integration/iac/terraform/terraform.md`
=> PORT-12046 Fix indentations

docs/build-your-software-catalog/custom-integration/webhook/examples/resources/general/_example_full_configuration.mdx, docs/build-your-software-catalog/custom-integration/webhook/webhook.md
=> add webhook search relation example, revise webhook page

docs/build-your-software-catalog/custom-integration/api/ci-cd/github-workflow/examples.md, docs/build-your-software-catalog/custom-integration/api/ci-cd/github-workflow/github-workflow.md
=> add gradle github action example, revise github action page

src/components/guides-section/GuidePage/GuidePage.jsx, static/img/guides/icons/Filter.svg
added filter svg icon and inserted before the Filters string at the main Guids page
- static/img/guides/icons/Filter.svg
- src/components/guides-section/GuidePage/GuidePage.jsx
=> filters icon in main Guides page

docs/promote-scorecards/promote-scorecards.md, docusaurus.config.js
=> update admonition, add release notes link

docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/example-member/_gitlab_exporter_example_member_blueprint.mdx
=> fixed JSON

docs/security.md
=> update security mfa docs

docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/aws-exporter/aws-exporter.md
=> update deprecation notice

docs/actions-and-automations/create-self-service-experiences/setup-ui-for-action/advanced-form-configurations.md, docs/sso-rbac/rbac/rbac.md
=> Hide users and teams

docs/customize-pages-dashboards-and-plugins/dashboards/dashboards.md
=> line chart clarification

docs/api-reference/port-api.info.mdx, docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/properties/properties.md, docs/build-your-software-catalog/customize-integrations/configure-mapping.md
=> add jwt expiration note, correct prop hide in table

docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira/jira.md, src/components/ocean-saas-specifics/default-settings.jsx
=> add oauth docs for jira

docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/example-project/_azuredevops_exporter_example_work_item_port_app_config.mdx
Following this commit to Ocean
https://github.com/port-labs/ocean/commit/32bf474df287d2a4fed9fb25d28389ca9d74ba46#diff-583fc09eda27e4b801bb21bda7ef9e6502dff16173d527aac0445005035a29e2R73
=> Azure Devops - Add "expand" parameter

docs/generalTemplates/_guide_template_for_ai.md
=> add guide template for ai

docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/datadog/datadog.md, src/components/ocean-saas-specifics/default-settings.jsx, src/components/ocean-saas-specifics/integration-settings.jsx
=> add datadog oauth docs

src/components/IntegrationsTable/styles.module.css
=> add mobile support to integrations component

docs/actions-and-automations/setup-backend/gitlab-pipeline/self-hosted.md, docs/actions-and-automations/setup-backend/webhook/circle-ci/circle-ci.md, docs/actions-and-automations/setup-backend/webhook/kafka/examples/__changelog-basic-change-listener-using-aws-lambda.md, docs/actions-and-automations/setup-backend/webhook/port-execution-agent/port-execution-agent.md, docs/actions-and-automations/setup-backend/webhook/terraform-cloud/terraform-cloud.md, docs/guides/all/execution-basic-runner-using-aws-lambda.md, docs/sso-rbac/sso-providers/oidc/azure-ad.md, docs/sso-rbac/sso-providers/oidc/oidc.md, docs/sso-rbac/sso-providers/oidc/okta.md, docs/sso-rbac/sso-providers/oidc/onelogin.md, docs/sso-rbac/sso-providers/saml/google-workspace.md, docs/sso-rbac/sso-providers/saml/jumpcloud.md, docs/troubleshooting.md
=> PORT-12547 Add support mail address where support is referenced

docs/actions-and-automations/define-automations/examples.md, src/components/guides-section/consts.js
=> add auto approve action example

docs/api-reference/security.mdx, docs/api-reference/sidebar.ts
=> PORT-12293 Add security page to the API reference with info about allowlists

docusaurus.config.js
=> update kapa config

.github/workflows/kapa-weekly-report.yml
=> add workflow to send kapa usage reports

docs/api-reference/security.mdx, docs/generalTemplates/_enterprise_feature_notice.md
=> PORT-12607 Add AWS PrivateLink docs to API security section

docs/guides/all/manage-resources-using-k8s-crds.md
Indicate that crdsToDiscover is a mapping parameter and not a than helm flag
- ...
- ...
=> Indicate that crdsToDiscover is a mapping parameter and not a than helm flag

docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace/dynatrace.md
Added dynatrace teams kind and added a relation between slo and monitored entities
- ...
- ...
=> Add dynatrace teams

docs/actions-and-automations/create-self-service-experiences/set-self-service-actions-rbac/dynamic-permissions.md, docs/build-your-software-catalog/set-catalog-rbac/examples.md, docs/customize-pages-dashboards-and-plugins/page/page-permissions.md, docs/resources.md
=> update team examples to use identifiers, add video

.github/workflows/kapa-weekly-report.yml
=> enrich kapa report

docs/build-your-software-catalog/custom-integration/custom-integration.md, docs/build-your-software-catalog/sync-data-to-catalog/sync-data-to-catalog.md, docs/generalTemplates/_ocean_contribution.md
=> add ocean contribution option

docs/build-your-software-catalog/customize-integrations/configure-mapping.md
added explanation for why integration deletes data from port
- ...
- ...
=> added more description to the entityDeletionThreshold

docs/actions-and-automations/create-self-service-experiences/send-link-to-action.md, src/components/ActionUrlGenerator/index.jsx, src/components/ActionUrlGenerator/styles.module.css
actions-and-automations/create-self-service-experiences/send-link-to-action
=> Add documentation on the ability to send a direct link with action inputs

docs/actions-and-automations/create-self-service-experiences/send-link-to-action.md, docs/customize-pages-dashboards-and-plugins/dashboards/dashboards.md
=> add internal markdown links section

docs/sso-rbac/rbac/as-blueprints.md, docs/sso-rbac/rbac/migration.md
Reverts port-labs/port-docs#2016
=> Revert "Port 12834 system blueprints in terraform"

docs/actions-and-automations/define-automations/examples.md, src/css/custom.css
=> add automation example

docs/actions-and-automations/create-self-service-experiences/set-self-service-actions-rbac/dynamic-permissions.md, docs/sso-rbac/rbac/as-blueprints.md
=> dynamic permissions fix

docs/actions-and-automations/create-self-service-experiences/create-self-service-experiences.md, docs/build-your-software-catalog/customize-integrations/configure-data-model/Iac/_category_.json, docs/build-your-software-catalog/customize-integrations/configure-data-model/relate-blueprints/_category_.json, docs/build-your-software-catalog/customize-integrations/configure-data-model/relate-blueprints/relate-blueprints.md, docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/_category_.json, docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/setup-blueprint.md
=> fix sidebar names, add action execution tip

docs/actions-and-automations/setup-backend/azure-pipeline/azure-pipeline.md, docs/actions-and-automations/setup-backend/jenkins-pipeline/jenkins-pipeline.md, docs/build-your-software-catalog/custom-integration/webhook/examples/git/_github.md, docs/build-your-software-catalog/custom-integration/webhook/examples/git/_gitlab.md, docs/build-your-software-catalog/custom-integration/webhook/examples/resources/bitbucket-server/_example_bitbucket_python_script.mdx, docs/build-your-software-catalog/custom-integration/webhook/examples/resources/general/_example_full_configuration.mdx, docs/build-your-software-catalog/custom-integration/webhook/examples/resources/github/_example_github_pr_configuration.mdx, docs/build-your-software-catalog/custom-integration/webhook/examples/stackhawk.md, docs/build-your-software-catalog/custom-integration/webhook/webhook.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty/pagerduty.md
Update note about known issues in header names in generic webhook
- ...
- ...
=> PORT-13247 Update header references in generic webhook to be lowercase

docs/customization.md
=> add title admonition

docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/_azuredevops_exporter_supported_resources.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/example-file/_azuredevops_exporter_example_file_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/example-file/_azuredevops_exporter_example_file_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/examples.md
Please also include the path for the added documents.
- File Blueprint (`docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/example-file/_azuredevops_exporter_example_file_blueprint.mdx`)
- File Mapping Examples (`docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/example-file/_azuredevops_exporter_example_file_port_app_config.mdx`)
Please also include the path for the updated documents.
- ADO Examples (`/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/examples.md`)
=> Add file kind to ADO

docs/generalTemplates/_airbyte_s3_destination_setup.md, docs/guides/all/ingest-hibob-data-via-airbyte-s3-and-webhook.md, docs/guides/all/ingest-okta-data-via-airbyte-s3-and-webhook.md, docs/guides/all/ingest-slack-data-via-airbyte-s3-and-webhook.md, src/components/guides-section/consts.js
=> revise 3 airbyte guides

docs/integrations-index.md
=> add kratix link and video

docs/guides/all/create-surveys.md
=> add survey guide callout

docs/actions-and-automations/create-self-service-experiences/setup-ui-for-action/advanced-form-configurations.md, docs/sso-rbac/rbac/as-blueprints.md, docs/sso-rbac/rbac/migration.md
=> clarifications for migration guide, fix uatb snippets

CONTRIBUTING.md
I've significantly enhanced the CONTRIBUTING.md file to provide more comprehensive guidance on documentation writing. Here's what I've added:
1. **Expanded tone & style guidelines**:
- Added guidance on sentence length and structure
- Emphasized active voice over passive voice
- Added tips on paragraph length and terminology consistency
2. **Enhanced guides & examples section**:
- Added specific guidance on structuring steps
- Included tips on using action verbs
- Added recommendations for providing context and expected outcomes
3. **Added a new "Technical writing best practices" section**:
- Emphasized clarity, consistency, and accuracy
- Added guidance on handling technical terms and jargon
- Included tips on using examples and version awareness
4. **Expanded existing sections with more …
=>  Improve contributing.md

docs/generalTemplates/_sso_auth0_endpoints.md, docs/generalTemplates/_sso_direct_url.md, docs/sso-rbac/sso-providers/oidc/azure-ad.md, docs/sso-rbac/sso-providers/oidc/oidc.md, docs/sso-rbac/sso-providers/oidc/okta.md, docs/sso-rbac/sso-providers/oidc/onelogin.md, docs/sso-rbac/sso-providers/saml/azure-ad.md, docs/sso-rbac/sso-providers/saml/google-workspace.md, docs/sso-rbac/sso-providers/saml/jumpcloud.md, docs/sso-rbac/sso-providers/saml/okta.md
=> add US authorization URL, and info note about direct login

src/css/custom.css
=> change navbar sidebar and toc active and hover color

docs/guides/implementation-guide/build/install-integrations.md, docs/guides/implementation-guide/launch/launch.md, docs/security.md
=> update security page

docs/guides/all/create-firehydrant-incident.md, docs/integrations-index.md, src/components/guides-section/consts.js
A guide to create FireHydrant incident from Port
docs/guides/all/create-firehydrant-incident.md
docs/integrations-index.md
src/components/guides-section/consts.js
=> Create FireHydrant incident from Port

src/theme/CodeBlock/index.js
=> update api address

docs/sso-rbac/rbac/as-blueprints.md
Reword documentation on ownership properties in RBAC blueprints
- As Blueprint (New)(`/sso-rbac/rbac/no-blueprints`)
=> PORT-13334-bug-improve-the-user-team-bp

docs/guides/implementation-guide/launch/launch.md, docs/guides/implementation-guide/plan/prepare-for-building.md, docs/guides/implementation-guide/start-here.md
=> Implementation guide improvements

docs/build-your-software-catalog/sync-data-to-catalog/templates/_ocean_saas_installation.mdx, docs/build-your-software-catalog/sync-data-to-catalog/templates/_ocean_saas_installation_oauth.mdx
=> fix live events template and syntax

src/components/ocean-saas-specifics/live-events.jsx
=> fix live events text

docs/guides/all/create-incident-io-incident.md, src/components/guides-section/consts.js
Create an incident.io incident using Port API
- ...
- ...
=> Create incident.io Incidents Using Synced Webhooks

docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk/snyk.md
Minor punctuation fix.
/docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/snyk/snyk.md
=> Update snyk.md (minor punctuation)

docs/actions-and-automations/setup-backend/jenkins-pipeline/jenkins-pipeline.md
=> Add US gateway addresses

package-lock.json, package.json
=> update lib versions

docs/build-your-software-catalog/sync-data-to-catalog/git/github/advanced.md
Add GitHub integration `closedPullRequests` option to the docs
N/A
`build-your-software-catalog/sync-data-to-catalog/git/github/advanced`
=> docs(gh): closedPullRequests

docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/setup-blueprint.md, docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket-cloud/installation.md
=> remove unnecessary screenshot

docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/resource-mapping-examples.md, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/examples.md
Made changes to both example pages.
- https://docs.port.io/build-your-software-catalog/sync-data-to-catalog/git/gitlab/examples/
- https://docs.port.io/build-your-software-catalog/sync-data-to-catalog/git/github/examples/resource-mapping-examples
=> First commit to branch with the relevant changes

docs/guides/all/ensure-production-readiness.md
Changed the value in scorecard schema from "on_call" to "pagerduty_oncall".
- https://docs.port.io/guides/all/ensure-production-readiness/#update-your-existing-services-scorecard
=> Fix property name in scorecard schema

docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/example-repository-folders/_gitlab_export_example_monorepo_port_app_config.mdx
=> Typo in GitLab folder mapping causing mapping to fail

docusaurus.config.js, src/components/KapaCallout/KapaCallout.jsx
=> change kapa title

docs/customize-pages-dashboards-and-plugins/dashboards/dashboards.md
Added iframe visualization note
- https://docs.port.io/customize-pages-dashboards-and-plugins/dashboards/#iframe-visualization
=> added iframe visualization note

docs/actions-and-automations/create-self-service-experiences/setup-ui-for-action/user-inputs/text.md, docs/customization.md
=> add multiline input section, remove autplay from accessibility videos

docs/ai-agents/slack-app.md
=> comment out unready content

docs/build-your-software-catalog/sync-data-to-catalog/feature-management/launchdarkly/_launchdarkly_one_time_docker_parameters.mdx, docs/build-your-software-catalog/sync-data-to-catalog/feature-management/launchdarkly/launchdarkly.md, src/components/ocean-saas-specifics/live-events.jsx
=> PORT-13774 Update Live Events Support for Launchdarkly

docs/api-reference/rate-limits.mdx
=> Modified rate limit threshold

docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/example-file/_azuredevops_exporter_example_file_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/example-file/_azuredevops_exporter_example_file_port_app_config.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/examples.md
=> BugFix - File content mapping in ADO 

src/components/guides-section/consts.js
=> Add Security tag to Guide

docs/generalTemplates/_port_api_available_regions.md, docs/generalTemplates/_port_region_parameter_explanation_template.md
=> move to port.io

docs/build-your-software-catalog/sync-data-to-catalog/git/github/self-hosted-installation.md
=> [Github] Bump self hosted version to `0.16.7`

docs/guides/all/create-and-track-dora-metrics-in-your-portal.md, docs/guides/all/create-and-use-surveys-in-your-portal.md, src/css/custom.css
=> add engineering360 videos to guides

docs/sso-rbac/sso-providers/saml/azure-ad.md, docs/sso-rbac/sso-providers/saml/google-workspace.md, docs/sso-rbac/sso-providers/saml/okta.md
=> Saml docs update

docs/guides/all/manage-integrations.md
fixed mapping for the guide because of the following changes: https://github.com/port-labs/ocean/pull/1624
- ...
- ...
=> Fix Monitor integrations guide

src/components/guides-section/consts.js
=> update guide use cases

docs/sso-rbac/rbac/migration.md
=> Migrate from relation to Ownership

docusaurus.config.js, package-lock.json, package.json
=> update docusaurus packages

docs/build-your-software-catalog/sync-data-to-catalog/project-management/jira/jira.md
Updated link for Jira Issue endpoint
- Jira( `/build-your-software-catalog/sync-data-to-catalog/project-management/jira/`)
=> Update Issue link

docs/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube/sonarqube.md
=> fix wrong app name

docs/build-your-software-catalog/set-catalog-rbac/set-catalog-rbac.md
Shouldn't have policy example in all tabs except policy
- ...
- ...
=> Update entities read RBAC example

docs/guides/all/send-typeform-survey-results-to-port.md, src/components/guides-section/consts.js
=> Send TypeForm survey response to Port

docs/build-your-software-catalog/sync-data-to-catalog/git/_port_yml_ingestion_pattern_template_parsed.md, docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/gitops/gitops.md
=> fix ADO GitOps kind file mapping

docs/search-and-query/comparison-operators.md
=> Add contains on array example

src/components/guides-section/GuideCard/GuideCard.jsx, src/components/guides-section/styles.css
=> make guide cards right clickable

docs/actions-and-automations/setup-backend/webhook/port-execution-agent/control-the-payload.md
Updated port-execution-agent/control-the-payload.md with fieldsToDecryptPaths
Path: https://docs.port.io/actions-and-automations/setup-backend/webhook/port-execution-agent/control-the-payload/
=> PORT-13568 add fieldsToDecryptPaths CTPL

docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/example-repository-admins/_github_exporter_example_admins_users_port_app_config.mdx
=> [Github] Add name to user kind

docs/guides/all/sync-argocd-app.md
Fix the ordered list indices with repeating 4
- Synchronize Argo CD Application (`https://docs.port.io/guides/all/sync-argocd-app`)
=> Fix ordered list indices

docs/sso-rbac/rbac/as-blueprints-beta.md, docs/sso-rbac/rbac/no-blueprints.md
=> change the deadline date

docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab-v2/GitLab-v2.md, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/gitlab.md
=> add info about incoming migration guide

docs/build-your-software-catalog/sync-data-to-catalog/sync-data-to-catalog.md
Added a note for monitoring and sync status page
- https://docs.port.io/build-your-software-catalog/sync-data-to-catalog/#monitoring-and-sync-status
=> add a note on live event

docs/customize-pages-dashboards-and-plugins/dashboards/dashboards.md
Added custom empty field documentation
- https://docs.port.io/customize-pages-dashboards-and-plugins/dashboards/
=> Added custom empty state documentation

docs/guides/all/open-github-issue.md
Fix incorrect URL in create Github issue API
- Create Github issue guide
=> Fix incorrect URL in create Github issue API

docs/guides/all/setup-pr-enricher-ai-agent.md
Update Pr-enricher-ai-agent to refine webhook URL and enhance PR comment workflow examples with GitHub App and PAT options.
- Set up Pull Request Enricher Agent (`/guides/all/setup-pr-enricher-ai-agent`)
=> PORTN-2929 Update Pr-enricher-ai-agent

docs/build-your-software-catalog/customize-integrations/configure-mapping.md
Added limitations for mapping relations section after talking to Raz.
- https://docs.port.io/build-your-software-catalog/customize-integrations/configure-mapping#limitations-1
=> Added limitations for mapping relations

docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/properties/mirror-property.md
Fixed the broken link reported in this Jira issue: https://getport.atlassian.net/browse/PORT-15197
- https://docs.port.io/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/properties/mirror-property/#-common-mirror-usage
=> fixed the broken link

docs/build-your-software-catalog/sync-data-to-catalog/git/_port_yml_ingestion_pattern_template_parsed.md
=> remove globs

docs/solutions/_category_.json
=> hide solutions page from sidebar

docs/security.md
=> Updates to security and compliance page text

archive/git-provider/github-exporter/self-hosted-installation.md, archive/self-service-actions/self-service-actions.md, contributor-license-agreement.txt, docs/actions-and-automations/setup-backend/gitlab-pipeline/self-hosted.md, docs/actions-and-automations/setup-backend/webhook/circle-ci/circle-ci.md, docs/actions-and-automations/setup-backend/webhook/kafka/examples/__changelog-basic-change-listener-using-aws-lambda.md, docs/actions-and-automations/setup-backend/webhook/port-execution-agent/port-execution-agent.md, docs/actions-and-automations/setup-backend/webhook/terraform-cloud/terraform-cloud.md, docs/api-reference/pages.mdx, docs/api-reference/security.mdx, docs/build-your-software-catalog/custom-integration/S3-integrations.md, docs/build-your-software-catalog/sync-data-to-catalog/apm-alerting/dynatrace/dynatrace.md, docs/build-your-software-catalog/sync-data-to-catalog/git/github/self-hosted-installation.md, docs/build-your-software-catalog/sync-data-to-catalog/incident-management/pagerduty/pagerduty.md, docs/guides/all/execution-basic-runner-using-aws-lambda.md, docs/guides/all/ingest-hibob-data-via-airbyte-s3-and-webhook.md, docs/guides/all/ingest-okta-data-via-airbyte-s3-and-webhook.md, docs/guides/all/ingest-slack-data-via-airbyte-s3-and-webhook.md, docs/guides/all/ingest-slack-data-via-fivetran-s3-and-webhook.md, docs/sso-rbac/sso-providers/oidc/azure-ad.md, docs/sso-rbac/sso-providers/oidc/oidc.md, docs/sso-rbac/sso-providers/oidc/okta.md, docs/sso-rbac/sso-providers/oidc/onelogin.md, docs/sso-rbac/sso-providers/saml/google-workspace.md, docs/sso-rbac/sso-providers/saml/jumpcloud.md, docs/troubleshooting.md
Changed support@getport.io to support.port.io
=> changed support@getport.io to support.port.io

static/js/embed-mode.js
- Implemented assume origin from query param to prevent hardcoding origins
- Removed extra execution on load
=> Embed docs - assume origin support

package-lock.json, package.json
=> update react version

docs/build-your-software-catalog/custom-integration/iac/pulumi/pulumi.md, docs/build-your-software-catalog/customize-integrations/configure-data-model/Iac/pulumi-managed-blueprint.md, docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/properties/array.md, docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/properties/boolean.md, docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/properties/calculation-property/calculation-property.md, docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/properties/datetime.md, docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/properties/email.md, docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/properties/mirror-property.md, docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/properties/number.md, docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/properties/object.md, docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/properties/proto.md, docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/properties/string.md, docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/properties/team.md, docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/properties/timer.md, docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/properties/url.md, docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/properties/user.md, docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/properties/yaml.md, docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/setup-blueprint.md, docs/customize-pages-dashboards-and-plugins/page/page-permissions.md
Updated the pulumi go import
Changed it from this:
- github.com/port-labs/pulumi-port/sdk/go/port
to this:
- github.com/port-labs/pulumi-port/sdk/v2/go/port
=> updated the pulumi go import to latest version

docs/build-your-software-catalog/custom-integration/api/ci-cd/azure-pipelines/examples.md, docs/build-your-software-catalog/custom-integration/api/ci-cd/circleci-workflow/examples.md, docs/build-your-software-catalog/custom-integration/api/ci-cd/gitlab-pipelines/examples.md, docs/build-your-software-catalog/custom-integration/api/ci-cd/jenkins-deployment/examples.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/aws/examples/examples.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/resource_templates/advanced.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/azure/resource_templates/resource_templates.md, docs/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/examples/examples.md, docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/examples.md, docs/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/mapping_extensions.md, docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/bitbucket-app/examples.md, docs/build-your-software-catalog/sync-data-to-catalog/git/bitbucket/bitbucket-cloud/examples.md, docs/build-your-software-catalog/sync-data-to-catalog/git/github-ocean/examples/examples.md, docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/example-repository-admins/_github_exporter_example_github_users_blueprint.mdx, docs/build-your-software-catalog/sync-data-to-catalog/git/github/examples/examples.md, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab-v2/examples.md, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab-v2/mapping_extensions.md, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/examples.md, docs/build-your-software-catalog/sync-data-to-catalog/git/gitlab/mapping_extensions.md, docs/build-your-software-catalog/sync-data-to-catalog/kubernetes-stack/kubernetes/basic-example.md
=> update git examples

docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/properties/_limit_field_restriction.mdx
Updated the note in the _limit_field_restriction template file.
=> fixed the note in limit_field_restriction template

.github/workflows/claude-pr-reviewer.yml, docs/ai-agents/build-an-ai-agent.md
=> PORT-15830: Add CC Github WF for docs review

docs/build-your-software-catalog/set-catalog-rbac/set-catalog-rbac.md
=> fix incorrect roles docs

docs/build-your-software-catalog/custom-integration/webhook/webhook.md
Added the note from this PR: https://github.com/port-labs/port-docs/pull/2661
As well as restyled the page with proper indentation. 
- https://docs.port.io/build-your-software-catalog/custom-integration/webhook/
=> Added note about payload size and restyled the page

docs/actions-and-automations/create-self-service-experiences/set-self-service-actions-rbac/dynamic-permissions.md
Changed the example as suggested in this Slack message: https://getport.slack.com/archives/C03LE6U5V1N/p1755723896632609
- https://docs.port.io/actions-and-automations/create-self-service-experiences/set-self-service-actions-rbac/dynamic-permissions/#prevent-self-approval
=> changed the example in dynamic permission page

docs/guides/all/humanitec-integration.md, docs/guides/templates/humanitec/_humanitec_deployment_deltas.mdx, docs/guides/templates/humanitec/_humanitec_exporter_cache.mdx, docs/guides/templates/humanitec/_humanitec_exporter_circuit_breaker.mdx, docs/guides/templates/humanitec/_humanitec_exporter_config.mdx, docs/guides/templates/humanitec/_humanitec_exporter_humanitec_client.mdx, docs/guides/templates/humanitec/_humanitec_exporter_port_client.mdx, docs/guides/templates/humanitec/_humanitec_exporter_retryable_http_client.mdx
The improved integration uses the bulk update endpoint, a retryable http client and a circuit breaker, making it more fault tolerant and faster.
- Updated `humanitec-integration.md` to include new configuration and circuit breaker components.
- Introduced `config.py` for integration constants and `circuit_breaker.py` for handling transient failures.
- Added `retryable_http_client.py` to manage HTTP requests with retry logic and circuit breaker protection.
- Updated `humanitec_deployment_deltas.mdx` schema to include new properties: `archived` and `contributors`.
- Enhanced `humanitec_exporter_humanitec_client.mdx` and `humanitec_exporter_port_client.mdx` to utilize the new retryable HTTP client.
- Added methods for bulk and batched entity upserts in the Port client.
- Humanitec …
=> Enhance Humanitec integration documentation and add new components

docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/properties/properties.md
Handled a couple of JIRA issues: 
- https://getport.atlassian.net/browse/PORT-9668
- https://getport.atlassian.net/browse/PORT-9670
- https://docs.port.io/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/properties/
=> Fixed two small issues in Properties page

docs/sso-rbac/rbac/rbac.md
=> remove delete sso team limitation

docs/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/properties/properties.md
This is the relevant JIRA issue: https://getport.atlassian.net/browse/PORT-9675
- https://docs.port.io/build-your-software-catalog/customize-integrations/configure-data-model/setup-blueprint/properties/#structure
=> Added . at the end of sentences in the property structure table

docs/build-your-software-catalog/sync-data-to-catalog/sync-data-to-catalog.md
Made changes to the installation methods table
- https://docs.port.io/build-your-software-catalog/sync-data-to-catalog/#installation-methods
=> Made changes to the installation methods table

docs/ai-interfaces/ai-agents/interact-with-ai-agents.md
Added explanation about the quota usage in agent invocation.
- docs/ai-interfaces/ai-agents/interact-with-ai-agents.md
=> Adds quota usage docs.

docs/build-your-software-catalog/set-catalog-rbac/set-catalog-rbac.md, docs/search-and-query/search-and-query.md
remove from close beta, minor adjustment to to examples
search-and-query/search-and-query.md
build-your-software-catalog/set-catalog-rbac/set-catalog-rbac.md
=> contextual-search close beta -> GA

docs/actions-and-automations/create-self-service-experiences/security/security.md
fix JIRA issue: https://getport.atlassian.net/browse/PORT-16254
Added the IP region.
=> fix reported issue security IP regions

docs/build-your-software-catalog/sync-data-to-catalog/sync-data-to-catalog.md
=> Changed the limit to be in the structure table instead of a callout

docs/guides/all/create-an-ec2-instance.md
=> PORT-16542 Fix typos and numbering in EC2 guide
